<?php

/**
 * BaseCorrespondence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $subject
 * @property integer $receiver_id
 * @property string $receiver_name
 * @property string $receiver_address
 * @property string $cc_addresses_list
 * @property string $notes
 * @property integer $sender_id
 * @property timestamp $backsheet_printed_date
 * @property date $delivered_date
 * @property date $returned_date
 * @property string $ctype
 * @property integer $user_file_id
 * @property integer $court_date_id
 * @property integer $receiver_group_id
 * @property integer $sent_by_id
 * @property integer $document_id
 * @property sfGuardUser $Receiver
 * @property sfGuardUser $Sender
 * @property UserFile $UserFile
 * @property CourtDate $CourtDate
 * @property sfGuardGroup $sfGuardGroup
 * @property SentBy $SentBy
 * @property Document $Document
 * @property Doctrine_Collection $FileAttachement
 * 
 * @method string              getSubject()                Returns the current record's "subject" value
 * @method integer             getReceiverId()             Returns the current record's "receiver_id" value
 * @method string              getReceiverName()           Returns the current record's "receiver_name" value
 * @method string              getReceiverAddress()        Returns the current record's "receiver_address" value
 * @method string              getCcAddressesList()        Returns the current record's "cc_addresses_list" value
 * @method string              getNotes()                  Returns the current record's "notes" value
 * @method integer             getSenderId()               Returns the current record's "sender_id" value
 * @method timestamp           getBacksheetPrintedDate()   Returns the current record's "backsheet_printed_date" value
 * @method date                getDeliveredDate()          Returns the current record's "delivered_date" value
 * @method date                getReturnedDate()           Returns the current record's "returned_date" value
 * @method string              getCtype()                  Returns the current record's "ctype" value
 * @method integer             getUserFileId()             Returns the current record's "user_file_id" value
 * @method integer             getCourtDateId()            Returns the current record's "court_date_id" value
 * @method integer             getReceiverGroupId()        Returns the current record's "receiver_group_id" value
 * @method integer             getSentById()               Returns the current record's "sent_by_id" value
 * @method integer             getDocumentId()             Returns the current record's "document_id" value
 * @method sfGuardUser         getReceiver()               Returns the current record's "Receiver" value
 * @method sfGuardUser         getSender()                 Returns the current record's "Sender" value
 * @method UserFile            getUserFile()               Returns the current record's "UserFile" value
 * @method CourtDate           getCourtDate()              Returns the current record's "CourtDate" value
 * @method sfGuardGroup        getSfGuardGroup()           Returns the current record's "sfGuardGroup" value
 * @method SentBy              getSentBy()                 Returns the current record's "SentBy" value
 * @method Document            getDocument()               Returns the current record's "Document" value
 * @method Doctrine_Collection getFileAttachement()        Returns the current record's "FileAttachement" collection
 * @method Correspondence      setSubject()                Sets the current record's "subject" value
 * @method Correspondence      setReceiverId()             Sets the current record's "receiver_id" value
 * @method Correspondence      setReceiverName()           Sets the current record's "receiver_name" value
 * @method Correspondence      setReceiverAddress()        Sets the current record's "receiver_address" value
 * @method Correspondence      setCcAddressesList()        Sets the current record's "cc_addresses_list" value
 * @method Correspondence      setNotes()                  Sets the current record's "notes" value
 * @method Correspondence      setSenderId()               Sets the current record's "sender_id" value
 * @method Correspondence      setBacksheetPrintedDate()   Sets the current record's "backsheet_printed_date" value
 * @method Correspondence      setDeliveredDate()          Sets the current record's "delivered_date" value
 * @method Correspondence      setReturnedDate()           Sets the current record's "returned_date" value
 * @method Correspondence      setCtype()                  Sets the current record's "ctype" value
 * @method Correspondence      setUserFileId()             Sets the current record's "user_file_id" value
 * @method Correspondence      setCourtDateId()            Sets the current record's "court_date_id" value
 * @method Correspondence      setReceiverGroupId()        Sets the current record's "receiver_group_id" value
 * @method Correspondence      setSentById()               Sets the current record's "sent_by_id" value
 * @method Correspondence      setDocumentId()             Sets the current record's "document_id" value
 * @method Correspondence      setReceiver()               Sets the current record's "Receiver" value
 * @method Correspondence      setSender()                 Sets the current record's "Sender" value
 * @method Correspondence      setUserFile()               Sets the current record's "UserFile" value
 * @method Correspondence      setCourtDate()              Sets the current record's "CourtDate" value
 * @method Correspondence      setSfGuardGroup()           Sets the current record's "sfGuardGroup" value
 * @method Correspondence      setSentBy()                 Sets the current record's "SentBy" value
 * @method Correspondence      setDocument()               Sets the current record's "Document" value
 * @method Correspondence      setFileAttachement()        Sets the current record's "FileAttachement" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorrespondence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('correspondence');
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('receiver_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('receiver_name', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('receiver_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cc_addresses_list', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('notes', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('sender_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('backsheet_printed_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('delivered_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('returned_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ctype', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('court_date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('receiver_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sent_by_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('document_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Receiver', array(
             'local' => 'receiver_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CourtDate', array(
             'local' => 'court_date_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup', array(
             'local' => 'receiver_group_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('SentBy', array(
             'local' => 'sent_by_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('FileAttachement', array(
             'local' => 'id',
             'foreign' => 'correspondence_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}