<?php

/**
 * BaseShortMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sms_from
 * @property string $sms_to
 * @property string $office
 * @property string $message
 * @property integer $user_id
 * @property integer $user_file_id
 * @property sfGuardUser $User
 * @property UserFile $UserFile
 * 
 * @method string       getSmsFrom()      Returns the current record's "sms_from" value
 * @method string       getSmsTo()        Returns the current record's "sms_to" value
 * @method string       getOffice()       Returns the current record's "office" value
 * @method string       getMessage()      Returns the current record's "message" value
 * @method integer      getUserId()       Returns the current record's "user_id" value
 * @method integer      getUserFileId()   Returns the current record's "user_file_id" value
 * @method sfGuardUser  getUser()         Returns the current record's "User" value
 * @method UserFile     getUserFile()     Returns the current record's "UserFile" value
 * @method ShortMessage setSmsFrom()      Sets the current record's "sms_from" value
 * @method ShortMessage setSmsTo()        Sets the current record's "sms_to" value
 * @method ShortMessage setOffice()       Sets the current record's "office" value
 * @method ShortMessage setMessage()      Sets the current record's "message" value
 * @method ShortMessage setUserId()       Sets the current record's "user_id" value
 * @method ShortMessage setUserFileId()   Sets the current record's "user_file_id" value
 * @method ShortMessage setUser()         Sets the current record's "User" value
 * @method ShortMessage setUserFile()     Sets the current record's "UserFile" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShortMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('short_message');
        $this->hasColumn('sms_from', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('sms_to', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('office', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}