<?php

/**
 * BaseFeeAgreementType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * @property boolean $is_active
 * @property Doctrine_Collection $FeeAgreement
 * 
 * @method string              getValue()        Returns the current record's "value" value
 * @method boolean             getIsActive()     Returns the current record's "is_active" value
 * @method Doctrine_Collection getFeeAgreement() Returns the current record's "FeeAgreement" collection
 * @method FeeAgreementType    setValue()        Sets the current record's "value" value
 * @method FeeAgreementType    setIsActive()     Sets the current record's "is_active" value
 * @method FeeAgreementType    setFeeAgreement() Sets the current record's "FeeAgreement" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeeAgreementType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fee_agreement_type');
        $this->hasColumn('value', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FeeAgreement', array(
             'local' => 'id',
             'foreign' => 'fee_agreement_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}