<?php

/**
 * BaseCompliance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $original_grant_date
 * @property string $specific_category_applied_in
 * @property string $12months_proof_of_means
 * @property date $12months_proof_of_means_date
 * @property string $2years_proof_of_means
 * @property date $2years_proof_of_means_date
 * @property string $release_custody_proof_of_means
 * @property string $docs_for_self_employment
 * @property string $bank_statements_for_3months
 * @property string $recent_payslip_employeer_letter
 * @property string $separation_certificate
 * @property string $letter_for_new_address
 * @property string $deteals_for_caveat_provided
 * @property string $client_instructions_on_file
 * @property string $charges
 * @property string $priors
 * @property string $centrelink_crn
 * @property date $expiry_date_on_hcc
 * @property string $pay_board_amount
 * @property string $name_of_fap
 * @property date $expiry_date_of_fap_hcc
 * @property string $fap_bank_statements_for_3months
 * @property string $negotiation_informant_prosecutor
 * @property string $final_result_letter_sent
 * @property string $worksheet_on_file
 * @property string $issues_with_this_grant_of_aid
 * @property integer $legal_aid_id
 * @property integer $who_live_with_id
 * @property LegalAid $LegalAid
 * @property WhoLiveWith $WhoLiveWith
 * 
 * @method date        getOriginalGrantDate()                Returns the current record's "original_grant_date" value
 * @method string      getSpecificCategoryAppliedIn()        Returns the current record's "specific_category_applied_in" value
 * @method string      get12monthsProofOfMeans()             Returns the current record's "12months_proof_of_means" value
 * @method date        get12monthsProofOfMeansDate()         Returns the current record's "12months_proof_of_means_date" value
 * @method string      get2yearsProofOfMeans()               Returns the current record's "2years_proof_of_means" value
 * @method date        get2yearsProofOfMeansDate()           Returns the current record's "2years_proof_of_means_date" value
 * @method string      getReleaseCustodyProofOfMeans()       Returns the current record's "release_custody_proof_of_means" value
 * @method string      getDocsForSelfEmployment()            Returns the current record's "docs_for_self_employment" value
 * @method string      getBankStatementsFor3months()         Returns the current record's "bank_statements_for_3months" value
 * @method string      getRecentPayslipEmployeerLetter()     Returns the current record's "recent_payslip_employeer_letter" value
 * @method string      getSeparationCertificate()            Returns the current record's "separation_certificate" value
 * @method string      getLetterForNewAddress()              Returns the current record's "letter_for_new_address" value
 * @method string      getDetealsForCaveatProvided()         Returns the current record's "deteals_for_caveat_provided" value
 * @method string      getClientInstructionsOnFile()         Returns the current record's "client_instructions_on_file" value
 * @method string      getCharges()                          Returns the current record's "charges" value
 * @method string      getPriors()                           Returns the current record's "priors" value
 * @method string      getCentrelinkCrn()                    Returns the current record's "centrelink_crn" value
 * @method date        getExpiryDateOnHcc()                  Returns the current record's "expiry_date_on_hcc" value
 * @method string      getPayBoardAmount()                   Returns the current record's "pay_board_amount" value
 * @method string      getNameOfFap()                        Returns the current record's "name_of_fap" value
 * @method date        getExpiryDateOfFapHcc()               Returns the current record's "expiry_date_of_fap_hcc" value
 * @method string      getFapBankStatementsFor3months()      Returns the current record's "fap_bank_statements_for_3months" value
 * @method string      getNegotiationInformantProsecutor()   Returns the current record's "negotiation_informant_prosecutor" value
 * @method string      getFinalResultLetterSent()            Returns the current record's "final_result_letter_sent" value
 * @method string      getWorksheetOnFile()                  Returns the current record's "worksheet_on_file" value
 * @method string      getIssuesWithThisGrantOfAid()         Returns the current record's "issues_with_this_grant_of_aid" value
 * @method integer     getLegalAidId()                       Returns the current record's "legal_aid_id" value
 * @method integer     getWhoLiveWithId()                    Returns the current record's "who_live_with_id" value
 * @method LegalAid    getLegalAid()                         Returns the current record's "LegalAid" value
 * @method WhoLiveWith getWhoLiveWith()                      Returns the current record's "WhoLiveWith" value
 * @method Compliance  setOriginalGrantDate()                Sets the current record's "original_grant_date" value
 * @method Compliance  setSpecificCategoryAppliedIn()        Sets the current record's "specific_category_applied_in" value
 * @method Compliance  set12monthsProofOfMeans()             Sets the current record's "12months_proof_of_means" value
 * @method Compliance  set12monthsProofOfMeansDate()         Sets the current record's "12months_proof_of_means_date" value
 * @method Compliance  set2yearsProofOfMeans()               Sets the current record's "2years_proof_of_means" value
 * @method Compliance  set2yearsProofOfMeansDate()           Sets the current record's "2years_proof_of_means_date" value
 * @method Compliance  setReleaseCustodyProofOfMeans()       Sets the current record's "release_custody_proof_of_means" value
 * @method Compliance  setDocsForSelfEmployment()            Sets the current record's "docs_for_self_employment" value
 * @method Compliance  setBankStatementsFor3months()         Sets the current record's "bank_statements_for_3months" value
 * @method Compliance  setRecentPayslipEmployeerLetter()     Sets the current record's "recent_payslip_employeer_letter" value
 * @method Compliance  setSeparationCertificate()            Sets the current record's "separation_certificate" value
 * @method Compliance  setLetterForNewAddress()              Sets the current record's "letter_for_new_address" value
 * @method Compliance  setDetealsForCaveatProvided()         Sets the current record's "deteals_for_caveat_provided" value
 * @method Compliance  setClientInstructionsOnFile()         Sets the current record's "client_instructions_on_file" value
 * @method Compliance  setCharges()                          Sets the current record's "charges" value
 * @method Compliance  setPriors()                           Sets the current record's "priors" value
 * @method Compliance  setCentrelinkCrn()                    Sets the current record's "centrelink_crn" value
 * @method Compliance  setExpiryDateOnHcc()                  Sets the current record's "expiry_date_on_hcc" value
 * @method Compliance  setPayBoardAmount()                   Sets the current record's "pay_board_amount" value
 * @method Compliance  setNameOfFap()                        Sets the current record's "name_of_fap" value
 * @method Compliance  setExpiryDateOfFapHcc()               Sets the current record's "expiry_date_of_fap_hcc" value
 * @method Compliance  setFapBankStatementsFor3months()      Sets the current record's "fap_bank_statements_for_3months" value
 * @method Compliance  setNegotiationInformantProsecutor()   Sets the current record's "negotiation_informant_prosecutor" value
 * @method Compliance  setFinalResultLetterSent()            Sets the current record's "final_result_letter_sent" value
 * @method Compliance  setWorksheetOnFile()                  Sets the current record's "worksheet_on_file" value
 * @method Compliance  setIssuesWithThisGrantOfAid()         Sets the current record's "issues_with_this_grant_of_aid" value
 * @method Compliance  setLegalAidId()                       Sets the current record's "legal_aid_id" value
 * @method Compliance  setWhoLiveWithId()                    Sets the current record's "who_live_with_id" value
 * @method Compliance  setLegalAid()                         Sets the current record's "LegalAid" value
 * @method Compliance  setWhoLiveWith()                      Sets the current record's "WhoLiveWith" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompliance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('compliance');
        $this->hasColumn('original_grant_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('specific_category_applied_in', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('12months_proof_of_means', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('12months_proof_of_means_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('2years_proof_of_means', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('2years_proof_of_means_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('release_custody_proof_of_means', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('docs_for_self_employment', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('bank_statements_for_3months', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('recent_payslip_employeer_letter', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('separation_certificate', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('letter_for_new_address', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('deteals_for_caveat_provided', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('client_instructions_on_file', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('charges', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('priors', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('centrelink_crn', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('expiry_date_on_hcc', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('pay_board_amount', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('name_of_fap', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('expiry_date_of_fap_hcc', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fap_bank_statements_for_3months', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('negotiation_informant_prosecutor', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('final_result_letter_sent', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('worksheet_on_file', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('issues_with_this_grant_of_aid', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('legal_aid_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('who_live_with_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LegalAid', array(
             'local' => 'legal_aid_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('WhoLiveWith', array(
             'local' => 'who_live_with_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}