<?php

/**
 * BaseUserFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $number
 * @property string $charge_first_name
 * @property string $charge_last_name
 * @property string $first_name
 * @property string $last_name
 * @property integer $honorific_id
 * @property integer $preferred_contact_id
 * @property boolean $correspondence_title
 * @property boolean $correspondence_real_name
 * @property integer $correspondence_sent_option
 * @property string $street
 * @property string $suburb
 * @property string $postcode
 * @property string $city
 * @property string $state
 * @property string $street2
 * @property string $suburb2
 * @property string $postcode2
 * @property string $city2
 * @property string $state2
 * @property string $home_phone
 * @property string $work_phone
 * @property string $mobile
 * @property string $other_phone
 * @property string $fax
 * @property string $email
 * @property date $first_instructions_date
 * @property string $case_number
 * @property string $instruction_on_file
 * @property string $instruction
 * @property string $barrister_backsheet_options
 * @property string $barrister_fee
 * @property string $in_custody
 * @property string $bail_on_this
 * @property integer $client_id
 * @property integer $solicitor_id
 * @property integer $informant_id
 * @property integer $prosecutor_id
 * @property integer $barrister_id
 * @property integer $prosecution_id
 * @property integer $prison_id
 * @property integer $status_id
 * @property Honorific $Honorific
 * @property PreferredContact $PreferredContact
 * @property sfGuardUser $Client
 * @property sfGuardUser $Solicitor
 * @property sfGuardUser $Informant
 * @property sfGuardUser $Prosecutor
 * @property sfGuardUser $Barrister
 * @property Agency $Prosecution
 * @property Agency $Prison
 * @property Status $Status
 * @property Doctrine_Collection $Brief
 * @property Doctrine_Collection $FileCharges
 * @property Doctrine_Collection $CommittalStream
 * @property Doctrine_Collection $Correspondence
 * @property Doctrine_Collection $FileCourtDates
 * @property Doctrine_Collection $CustodyVisit
 * @property Doctrine_Collection $Document
 * @property Doctrine_Collection $FileFeeAgreements
 * @property Doctrine_Collection $FileAttachement
 * @property Doctrine_Collection $FileNote
 * @property Doctrine_Collection $LegalAid
 * @property Doctrine_Collection $ShortMessage
 * @property Doctrine_Collection $Task
 * 
 * @method string              getNumber()                      Returns the current record's "number" value
 * @method string              getChargeFirstName()             Returns the current record's "charge_first_name" value
 * @method string              getChargeLastName()              Returns the current record's "charge_last_name" value
 * @method string              getFirstName()                   Returns the current record's "first_name" value
 * @method string              getLastName()                    Returns the current record's "last_name" value
 * @method integer             getHonorificId()                 Returns the current record's "honorific_id" value
 * @method integer             getPreferredContactId()          Returns the current record's "preferred_contact_id" value
 * @method boolean             getCorrespondenceTitle()         Returns the current record's "correspondence_title" value
 * @method boolean             getCorrespondenceRealName()      Returns the current record's "correspondence_real_name" value
 * @method integer             getCorrespondenceSentOption()    Returns the current record's "correspondence_sent_option" value
 * @method string              getStreet()                      Returns the current record's "street" value
 * @method string              getSuburb()                      Returns the current record's "suburb" value
 * @method string              getPostcode()                    Returns the current record's "postcode" value
 * @method string              getCity()                        Returns the current record's "city" value
 * @method string              getState()                       Returns the current record's "state" value
 * @method string              getStreet2()                     Returns the current record's "street2" value
 * @method string              getSuburb2()                     Returns the current record's "suburb2" value
 * @method string              getPostcode2()                   Returns the current record's "postcode2" value
 * @method string              getCity2()                       Returns the current record's "city2" value
 * @method string              getState2()                      Returns the current record's "state2" value
 * @method string              getHomePhone()                   Returns the current record's "home_phone" value
 * @method string              getWorkPhone()                   Returns the current record's "work_phone" value
 * @method string              getMobile()                      Returns the current record's "mobile" value
 * @method string              getOtherPhone()                  Returns the current record's "other_phone" value
 * @method string              getFax()                         Returns the current record's "fax" value
 * @method string              getEmail()                       Returns the current record's "email" value
 * @method date                getFirstInstructionsDate()       Returns the current record's "first_instructions_date" value
 * @method string              getCaseNumber()                  Returns the current record's "case_number" value
 * @method string              getInstructionOnFile()           Returns the current record's "instruction_on_file" value
 * @method string              getInstruction()                 Returns the current record's "instruction" value
 * @method string              getBarristerBacksheetOptions()   Returns the current record's "barrister_backsheet_options" value
 * @method string              getBarristerFee()                Returns the current record's "barrister_fee" value
 * @method string              getInCustody()                   Returns the current record's "in_custody" value
 * @method string              getBailOnThis()                  Returns the current record's "bail_on_this" value
 * @method integer             getClientId()                    Returns the current record's "client_id" value
 * @method integer             getSolicitorId()                 Returns the current record's "solicitor_id" value
 * @method integer             getInformantId()                 Returns the current record's "informant_id" value
 * @method integer             getProsecutorId()                Returns the current record's "prosecutor_id" value
 * @method integer             getBarristerId()                 Returns the current record's "barrister_id" value
 * @method integer             getProsecutionId()               Returns the current record's "prosecution_id" value
 * @method integer             getPrisonId()                    Returns the current record's "prison_id" value
 * @method integer             getStatusId()                    Returns the current record's "status_id" value
 * @method Honorific           getHonorific()                   Returns the current record's "Honorific" value
 * @method PreferredContact    getPreferredContact()            Returns the current record's "PreferredContact" value
 * @method sfGuardUser         getClient()                      Returns the current record's "Client" value
 * @method sfGuardUser         getSolicitor()                   Returns the current record's "Solicitor" value
 * @method sfGuardUser         getInformant()                   Returns the current record's "Informant" value
 * @method sfGuardUser         getProsecutor()                  Returns the current record's "Prosecutor" value
 * @method sfGuardUser         getBarrister()                   Returns the current record's "Barrister" value
 * @method Agency              getProsecution()                 Returns the current record's "Prosecution" value
 * @method Agency              getPrison()                      Returns the current record's "Prison" value
 * @method Status              getStatus()                      Returns the current record's "Status" value
 * @method Doctrine_Collection getBrief()                       Returns the current record's "Brief" collection
 * @method Doctrine_Collection getFileCharges()                 Returns the current record's "FileCharges" collection
 * @method Doctrine_Collection getCommittalStream()             Returns the current record's "CommittalStream" collection
 * @method Doctrine_Collection getCorrespondence()              Returns the current record's "Correspondence" collection
 * @method Doctrine_Collection getFileCourtDates()              Returns the current record's "FileCourtDates" collection
 * @method Doctrine_Collection getCustodyVisit()                Returns the current record's "CustodyVisit" collection
 * @method Doctrine_Collection getDocument()                    Returns the current record's "Document" collection
 * @method Doctrine_Collection getFileFeeAgreements()           Returns the current record's "FileFeeAgreements" collection
 * @method Doctrine_Collection getFileAttachement()             Returns the current record's "FileAttachement" collection
 * @method Doctrine_Collection getFileNote()                    Returns the current record's "FileNote" collection
 * @method Doctrine_Collection getLegalAid()                    Returns the current record's "LegalAid" collection
 * @method Doctrine_Collection getShortMessage()                Returns the current record's "ShortMessage" collection
 * @method Doctrine_Collection getTask()                        Returns the current record's "Task" collection
 * @method UserFile            setNumber()                      Sets the current record's "number" value
 * @method UserFile            setChargeFirstName()             Sets the current record's "charge_first_name" value
 * @method UserFile            setChargeLastName()              Sets the current record's "charge_last_name" value
 * @method UserFile            setFirstName()                   Sets the current record's "first_name" value
 * @method UserFile            setLastName()                    Sets the current record's "last_name" value
 * @method UserFile            setHonorificId()                 Sets the current record's "honorific_id" value
 * @method UserFile            setPreferredContactId()          Sets the current record's "preferred_contact_id" value
 * @method UserFile            setCorrespondenceTitle()         Sets the current record's "correspondence_title" value
 * @method UserFile            setCorrespondenceRealName()      Sets the current record's "correspondence_real_name" value
 * @method UserFile            setCorrespondenceSentOption()    Sets the current record's "correspondence_sent_option" value
 * @method UserFile            setStreet()                      Sets the current record's "street" value
 * @method UserFile            setSuburb()                      Sets the current record's "suburb" value
 * @method UserFile            setPostcode()                    Sets the current record's "postcode" value
 * @method UserFile            setCity()                        Sets the current record's "city" value
 * @method UserFile            setState()                       Sets the current record's "state" value
 * @method UserFile            setStreet2()                     Sets the current record's "street2" value
 * @method UserFile            setSuburb2()                     Sets the current record's "suburb2" value
 * @method UserFile            setPostcode2()                   Sets the current record's "postcode2" value
 * @method UserFile            setCity2()                       Sets the current record's "city2" value
 * @method UserFile            setState2()                      Sets the current record's "state2" value
 * @method UserFile            setHomePhone()                   Sets the current record's "home_phone" value
 * @method UserFile            setWorkPhone()                   Sets the current record's "work_phone" value
 * @method UserFile            setMobile()                      Sets the current record's "mobile" value
 * @method UserFile            setOtherPhone()                  Sets the current record's "other_phone" value
 * @method UserFile            setFax()                         Sets the current record's "fax" value
 * @method UserFile            setEmail()                       Sets the current record's "email" value
 * @method UserFile            setFirstInstructionsDate()       Sets the current record's "first_instructions_date" value
 * @method UserFile            setCaseNumber()                  Sets the current record's "case_number" value
 * @method UserFile            setInstructionOnFile()           Sets the current record's "instruction_on_file" value
 * @method UserFile            setInstruction()                 Sets the current record's "instruction" value
 * @method UserFile            setBarristerBacksheetOptions()   Sets the current record's "barrister_backsheet_options" value
 * @method UserFile            setBarristerFee()                Sets the current record's "barrister_fee" value
 * @method UserFile            setInCustody()                   Sets the current record's "in_custody" value
 * @method UserFile            setBailOnThis()                  Sets the current record's "bail_on_this" value
 * @method UserFile            setClientId()                    Sets the current record's "client_id" value
 * @method UserFile            setSolicitorId()                 Sets the current record's "solicitor_id" value
 * @method UserFile            setInformantId()                 Sets the current record's "informant_id" value
 * @method UserFile            setProsecutorId()                Sets the current record's "prosecutor_id" value
 * @method UserFile            setBarristerId()                 Sets the current record's "barrister_id" value
 * @method UserFile            setProsecutionId()               Sets the current record's "prosecution_id" value
 * @method UserFile            setPrisonId()                    Sets the current record's "prison_id" value
 * @method UserFile            setStatusId()                    Sets the current record's "status_id" value
 * @method UserFile            setHonorific()                   Sets the current record's "Honorific" value
 * @method UserFile            setPreferredContact()            Sets the current record's "PreferredContact" value
 * @method UserFile            setClient()                      Sets the current record's "Client" value
 * @method UserFile            setSolicitor()                   Sets the current record's "Solicitor" value
 * @method UserFile            setInformant()                   Sets the current record's "Informant" value
 * @method UserFile            setProsecutor()                  Sets the current record's "Prosecutor" value
 * @method UserFile            setBarrister()                   Sets the current record's "Barrister" value
 * @method UserFile            setProsecution()                 Sets the current record's "Prosecution" value
 * @method UserFile            setPrison()                      Sets the current record's "Prison" value
 * @method UserFile            setStatus()                      Sets the current record's "Status" value
 * @method UserFile            setBrief()                       Sets the current record's "Brief" collection
 * @method UserFile            setFileCharges()                 Sets the current record's "FileCharges" collection
 * @method UserFile            setCommittalStream()             Sets the current record's "CommittalStream" collection
 * @method UserFile            setCorrespondence()              Sets the current record's "Correspondence" collection
 * @method UserFile            setFileCourtDates()              Sets the current record's "FileCourtDates" collection
 * @method UserFile            setCustodyVisit()                Sets the current record's "CustodyVisit" collection
 * @method UserFile            setDocument()                    Sets the current record's "Document" collection
 * @method UserFile            setFileFeeAgreements()           Sets the current record's "FileFeeAgreements" collection
 * @method UserFile            setFileAttachement()             Sets the current record's "FileAttachement" collection
 * @method UserFile            setFileNote()                    Sets the current record's "FileNote" collection
 * @method UserFile            setLegalAid()                    Sets the current record's "LegalAid" collection
 * @method UserFile            setShortMessage()                Sets the current record's "ShortMessage" collection
 * @method UserFile            setTask()                        Sets the current record's "Task" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_file');
        $this->hasColumn('number', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 120,
             ));
        $this->hasColumn('charge_first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('charge_last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('honorific_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('preferred_contact_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('correspondence_title', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('correspondence_real_name', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('correspondence_sent_option', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('street', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('suburb', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('postcode', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('city', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('state', 'string', 30, array(
             'type' => 'string',
             'default' => 'VIC',
             'length' => 30,
             ));
        $this->hasColumn('street2', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('suburb2', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('postcode2', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('city2', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('state2', 'string', 30, array(
             'type' => 'string',
             'default' => 'VIC',
             'length' => 30,
             ));
        $this->hasColumn('home_phone', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('work_phone', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('mobile', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('other_phone', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('fax', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('email', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('first_instructions_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('case_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('instruction_on_file', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('instruction', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('barrister_backsheet_options', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('barrister_fee', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('in_custody', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('bail_on_this', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('solicitor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('informant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('prosecutor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('barrister_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('prosecution_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('prison_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('case_number_idx', array(
             'fields' => 'case_number',
             ));
        $this->index('charge_first_name_idx', array(
             'fields' => 'charge_first_name',
             ));
        $this->index('charge_last_name_idx', array(
             'fields' => 'charge_last_name',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Honorific', array(
             'local' => 'honorific_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('PreferredContact', array(
             'local' => 'preferred_contact_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Solicitor', array(
             'local' => 'solicitor_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Informant', array(
             'local' => 'informant_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Prosecutor', array(
             'local' => 'prosecutor_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Barrister', array(
             'local' => 'barrister_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Agency as Prosecution', array(
             'local' => 'prosecution_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Agency as Prison', array(
             'local' => 'prison_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Status', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Brief', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('Charge as FileCharges', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('CommittalStream', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('Correspondence', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('CourtDate as FileCourtDates', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('CustodyVisit', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('Document', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('FeeAgreement as FileFeeAgreements', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('FileAttachement', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('FileNote', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('LegalAid', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('ShortMessage', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $this->hasMany('Task', array(
             'local' => 'id',
             'foreign' => 'user_file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}