<?php

/**
 * BaseFileNote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date
 * @property string $note_by
 * @property string $note_to
 * @property string $note
 * @property boolean $is_by_phone
 * @property integer $user_file_id
 * @property UserFile $UserFile
 * 
 * @method timestamp getDate()         Returns the current record's "date" value
 * @method string    getNoteBy()       Returns the current record's "note_by" value
 * @method string    getNoteTo()       Returns the current record's "note_to" value
 * @method string    getNote()         Returns the current record's "note" value
 * @method boolean   getIsByPhone()    Returns the current record's "is_by_phone" value
 * @method integer   getUserFileId()   Returns the current record's "user_file_id" value
 * @method UserFile  getUserFile()     Returns the current record's "UserFile" value
 * @method FileNote  setDate()         Sets the current record's "date" value
 * @method FileNote  setNoteBy()       Sets the current record's "note_by" value
 * @method FileNote  setNoteTo()       Sets the current record's "note_to" value
 * @method FileNote  setNote()         Sets the current record's "note" value
 * @method FileNote  setIsByPhone()    Sets the current record's "is_by_phone" value
 * @method FileNote  setUserFileId()   Sets the current record's "user_file_id" value
 * @method FileNote  setUserFile()     Sets the current record's "UserFile" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileNote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_note');
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('note_by', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('note_to', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('note', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('is_by_phone', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}