<?php

/**
 * BaseHonorific
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * @property string $abbreviation
 * @property string $type
 * @property boolean $is_active
 * @property Doctrine_Collection $sfGuardUserProfile
 * @property Doctrine_Collection $UserFile
 * 
 * @method string              getValue()              Returns the current record's "value" value
 * @method string              getAbbreviation()       Returns the current record's "abbreviation" value
 * @method string              getType()               Returns the current record's "type" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method Doctrine_Collection getSfGuardUserProfile() Returns the current record's "sfGuardUserProfile" collection
 * @method Doctrine_Collection getUserFile()           Returns the current record's "UserFile" collection
 * @method Honorific           setValue()              Sets the current record's "value" value
 * @method Honorific           setAbbreviation()       Sets the current record's "abbreviation" value
 * @method Honorific           setType()               Sets the current record's "type" value
 * @method Honorific           setIsActive()           Sets the current record's "is_active" value
 * @method Honorific           setSfGuardUserProfile() Sets the current record's "sfGuardUserProfile" collection
 * @method Honorific           setUserFile()           Sets the current record's "UserFile" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHonorific extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('honorific');
        $this->hasColumn('value', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('abbreviation', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'default' => 'CIVIL',
             'length' => 20,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'honorific_id'));

        $this->hasMany('UserFile', array(
             'local' => 'id',
             'foreign' => 'honorific_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}