<?php

/**
 * BaseCommittalStream
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $form_25_sent_date
 * @property date $hub_due_date
 * @property date $received_date
 * @property string $form_32_required
 * @property date $form_32_due_date
 * @property date $form_32_filled_date
 * @property integer $user_file_id
 * @property integer $court_date_id
 * @property integer $brief_status_id
 * @property UserFile $UserFile
 * @property CourtDate $CourtDate
 * @property Status $BriefStatus
 * 
 * @method date            getForm25SentDate()      Returns the current record's "form_25_sent_date" value
 * @method date            getHubDueDate()          Returns the current record's "hub_due_date" value
 * @method date            getReceivedDate()        Returns the current record's "received_date" value
 * @method string          getForm32Required()      Returns the current record's "form_32_required" value
 * @method date            getForm32DueDate()       Returns the current record's "form_32_due_date" value
 * @method date            getForm32FilledDate()    Returns the current record's "form_32_filled_date" value
 * @method integer         getUserFileId()          Returns the current record's "user_file_id" value
 * @method integer         getCourtDateId()         Returns the current record's "court_date_id" value
 * @method integer         getBriefStatusId()       Returns the current record's "brief_status_id" value
 * @method UserFile        getUserFile()            Returns the current record's "UserFile" value
 * @method CourtDate       getCourtDate()           Returns the current record's "CourtDate" value
 * @method Status          getBriefStatus()         Returns the current record's "BriefStatus" value
 * @method CommittalStream setForm25SentDate()      Sets the current record's "form_25_sent_date" value
 * @method CommittalStream setHubDueDate()          Sets the current record's "hub_due_date" value
 * @method CommittalStream setReceivedDate()        Sets the current record's "received_date" value
 * @method CommittalStream setForm32Required()      Sets the current record's "form_32_required" value
 * @method CommittalStream setForm32DueDate()       Sets the current record's "form_32_due_date" value
 * @method CommittalStream setForm32FilledDate()    Sets the current record's "form_32_filled_date" value
 * @method CommittalStream setUserFileId()          Sets the current record's "user_file_id" value
 * @method CommittalStream setCourtDateId()         Sets the current record's "court_date_id" value
 * @method CommittalStream setBriefStatusId()       Sets the current record's "brief_status_id" value
 * @method CommittalStream setUserFile()            Sets the current record's "UserFile" value
 * @method CommittalStream setCourtDate()           Sets the current record's "CourtDate" value
 * @method CommittalStream setBriefStatus()         Sets the current record's "BriefStatus" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommittalStream extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('committal_stream');
        $this->hasColumn('form_25_sent_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('hub_due_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('received_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('form_32_required', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('form_32_due_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('form_32_filled_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('court_date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('brief_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CourtDate', array(
             'local' => 'court_date_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Status as BriefStatus', array(
             'local' => 'brief_status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}