<?php

/**
 * BaseDisbursement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $provider
 * @property decimal $amount
 * @property string $invoice_number
 * @property date $date
 * @property string $paid
 * @property integer $disbursement_type_id
 * @property integer $court_date_id
 * @property DisbursementType $DisbursementType
 * @property CourtDate $CourtDate
 * 
 * @method string           getProvider()             Returns the current record's "provider" value
 * @method decimal          getAmount()               Returns the current record's "amount" value
 * @method string           getInvoiceNumber()        Returns the current record's "invoice_number" value
 * @method date             getDate()                 Returns the current record's "date" value
 * @method string           getPaid()                 Returns the current record's "paid" value
 * @method integer          getDisbursementTypeId()   Returns the current record's "disbursement_type_id" value
 * @method integer          getCourtDateId()          Returns the current record's "court_date_id" value
 * @method DisbursementType getDisbursementType()     Returns the current record's "DisbursementType" value
 * @method CourtDate        getCourtDate()            Returns the current record's "CourtDate" value
 * @method Disbursement     setProvider()             Sets the current record's "provider" value
 * @method Disbursement     setAmount()               Sets the current record's "amount" value
 * @method Disbursement     setInvoiceNumber()        Sets the current record's "invoice_number" value
 * @method Disbursement     setDate()                 Sets the current record's "date" value
 * @method Disbursement     setPaid()                 Sets the current record's "paid" value
 * @method Disbursement     setDisbursementTypeId()   Sets the current record's "disbursement_type_id" value
 * @method Disbursement     setCourtDateId()          Sets the current record's "court_date_id" value
 * @method Disbursement     setDisbursementType()     Sets the current record's "DisbursementType" value
 * @method Disbursement     setCourtDate()            Sets the current record's "CourtDate" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDisbursement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('disbursement');
        $this->hasColumn('provider', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             'notnull' => true,
             ));
        $this->hasColumn('invoice_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('paid', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('disbursement_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('court_date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DisbursementType', array(
             'local' => 'disbursement_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('CourtDate', array(
             'local' => 'court_date_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}