<?php

/**
 * BaseLegalAid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $reference_number
 * @property date $date_sent_given
 * @property date $date_aided_for
 * @property date $last_date_invoiced
 * @property integer $user_file_id
 * @property integer $office_id
 * @property integer $assigment_officer_id
 * @property integer $vla_app_status_id
 * @property integer $aid_status_id
 * @property UserFile $UserFile
 * @property Agency $Office
 * @property sfGuardUser $AssignmentOfficer
 * @property Status $VlaStatus
 * @property Status $AidStatus
 * @property Doctrine_Collection $AidGrant
 * @property Doctrine_Collection $Compliance
 * 
 * @method string              getReferenceNumber()      Returns the current record's "reference_number" value
 * @method date                getDateSentGiven()        Returns the current record's "date_sent_given" value
 * @method date                getDateAidedFor()         Returns the current record's "date_aided_for" value
 * @method date                getLastDateInvoiced()     Returns the current record's "last_date_invoiced" value
 * @method integer             getUserFileId()           Returns the current record's "user_file_id" value
 * @method integer             getOfficeId()             Returns the current record's "office_id" value
 * @method integer             getAssigmentOfficerId()   Returns the current record's "assigment_officer_id" value
 * @method integer             getVlaAppStatusId()       Returns the current record's "vla_app_status_id" value
 * @method integer             getAidStatusId()          Returns the current record's "aid_status_id" value
 * @method UserFile            getUserFile()             Returns the current record's "UserFile" value
 * @method Agency              getOffice()               Returns the current record's "Office" value
 * @method sfGuardUser         getAssignmentOfficer()    Returns the current record's "AssignmentOfficer" value
 * @method Status              getVlaStatus()            Returns the current record's "VlaStatus" value
 * @method Status              getAidStatus()            Returns the current record's "AidStatus" value
 * @method Doctrine_Collection getAidGrant()             Returns the current record's "AidGrant" collection
 * @method Doctrine_Collection getCompliance()           Returns the current record's "Compliance" collection
 * @method LegalAid            setReferenceNumber()      Sets the current record's "reference_number" value
 * @method LegalAid            setDateSentGiven()        Sets the current record's "date_sent_given" value
 * @method LegalAid            setDateAidedFor()         Sets the current record's "date_aided_for" value
 * @method LegalAid            setLastDateInvoiced()     Sets the current record's "last_date_invoiced" value
 * @method LegalAid            setUserFileId()           Sets the current record's "user_file_id" value
 * @method LegalAid            setOfficeId()             Sets the current record's "office_id" value
 * @method LegalAid            setAssigmentOfficerId()   Sets the current record's "assigment_officer_id" value
 * @method LegalAid            setVlaAppStatusId()       Sets the current record's "vla_app_status_id" value
 * @method LegalAid            setAidStatusId()          Sets the current record's "aid_status_id" value
 * @method LegalAid            setUserFile()             Sets the current record's "UserFile" value
 * @method LegalAid            setOffice()               Sets the current record's "Office" value
 * @method LegalAid            setAssignmentOfficer()    Sets the current record's "AssignmentOfficer" value
 * @method LegalAid            setVlaStatus()            Sets the current record's "VlaStatus" value
 * @method LegalAid            setAidStatus()            Sets the current record's "AidStatus" value
 * @method LegalAid            setAidGrant()             Sets the current record's "AidGrant" collection
 * @method LegalAid            setCompliance()           Sets the current record's "Compliance" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLegalAid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('legal_aid');
        $this->hasColumn('reference_number', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('date_sent_given', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_aided_for', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('last_date_invoiced', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('office_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('assigment_officer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('vla_app_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('aid_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Agency as Office', array(
             'local' => 'office_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as AssignmentOfficer', array(
             'local' => 'assigment_officer_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Status as VlaStatus', array(
             'local' => 'vla_app_status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Status as AidStatus', array(
             'local' => 'aid_status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('AidGrant', array(
             'local' => 'id',
             'foreign' => 'legal_aid_id'));

        $this->hasMany('Compliance', array(
             'local' => 'id',
             'foreign' => 'legal_aid_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}