<?php

/**
 * BaseFeeDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $amount
 * @property decimal $barrister_fee
 * @property decimal $disbursement
 * @property decimal $preparation_fee
 * @property decimal $appearance_fee
 * @property timestamp $date
 * @property string $comment
 * @property integer $fee_id
 * @property integer $type_id
 * @property integer $by_who_id
 * @property Fee $Fee
 * @property FeeDetailType $FeeDetailType
 * @property sfGuardUser $ByWho
 * 
 * @method decimal       getAmount()          Returns the current record's "amount" value
 * @method decimal       getBarristerFee()    Returns the current record's "barrister_fee" value
 * @method decimal       getDisbursement()    Returns the current record's "disbursement" value
 * @method decimal       getPreparationFee()  Returns the current record's "preparation_fee" value
 * @method decimal       getAppearanceFee()   Returns the current record's "appearance_fee" value
 * @method timestamp     getDate()            Returns the current record's "date" value
 * @method string        getComment()         Returns the current record's "comment" value
 * @method integer       getFeeId()           Returns the current record's "fee_id" value
 * @method integer       getTypeId()          Returns the current record's "type_id" value
 * @method integer       getByWhoId()         Returns the current record's "by_who_id" value
 * @method Fee           getFee()             Returns the current record's "Fee" value
 * @method FeeDetailType getFeeDetailType()   Returns the current record's "FeeDetailType" value
 * @method sfGuardUser   getByWho()           Returns the current record's "ByWho" value
 * @method FeeDetail     setAmount()          Sets the current record's "amount" value
 * @method FeeDetail     setBarristerFee()    Sets the current record's "barrister_fee" value
 * @method FeeDetail     setDisbursement()    Sets the current record's "disbursement" value
 * @method FeeDetail     setPreparationFee()  Sets the current record's "preparation_fee" value
 * @method FeeDetail     setAppearanceFee()   Sets the current record's "appearance_fee" value
 * @method FeeDetail     setDate()            Sets the current record's "date" value
 * @method FeeDetail     setComment()         Sets the current record's "comment" value
 * @method FeeDetail     setFeeId()           Sets the current record's "fee_id" value
 * @method FeeDetail     setTypeId()          Sets the current record's "type_id" value
 * @method FeeDetail     setByWhoId()         Sets the current record's "by_who_id" value
 * @method FeeDetail     setFee()             Sets the current record's "Fee" value
 * @method FeeDetail     setFeeDetailType()   Sets the current record's "FeeDetailType" value
 * @method FeeDetail     setByWho()           Sets the current record's "ByWho" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeeDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fee_detail');
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             'notnull' => true,
             ));
        $this->hasColumn('barrister_fee', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('disbursement', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('preparation_fee', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('appearance_fee', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('by_who_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Fee', array(
             'local' => 'fee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FeeDetailType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as ByWho', array(
             'local' => 'by_who_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}