<?php

/**
 * BaseBrief
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $request1
 * @property date $request2
 * @property date $request3
 * @property date $request4
 * @property string $interview_recording
 * @property string $scanned
 * @property string $hub_scanned
 * @property string $depositions_added
 * @property string $roi_tape_received
 * @property string $photographs_added
 * @property string $priors_received
 * @property string $statements_received
 * @property string $charges_received
 * @property string $summary_received
 * @property integer $user_file_id
 * @property integer $status_id
 * @property UserFile $UserFile
 * @property Status $Status
 * @property Doctrine_Collection $BriefAdditionalMaterial
 * 
 * @method date                getRequest1()                Returns the current record's "request1" value
 * @method date                getRequest2()                Returns the current record's "request2" value
 * @method date                getRequest3()                Returns the current record's "request3" value
 * @method date                getRequest4()                Returns the current record's "request4" value
 * @method string              getInterviewRecording()      Returns the current record's "interview_recording" value
 * @method string              getScanned()                 Returns the current record's "scanned" value
 * @method string              getHubScanned()              Returns the current record's "hub_scanned" value
 * @method string              getDepositionsAdded()        Returns the current record's "depositions_added" value
 * @method string              getRoiTapeReceived()         Returns the current record's "roi_tape_received" value
 * @method string              getPhotographsAdded()        Returns the current record's "photographs_added" value
 * @method string              getPriorsReceived()          Returns the current record's "priors_received" value
 * @method string              getStatementsReceived()      Returns the current record's "statements_received" value
 * @method string              getChargesReceived()         Returns the current record's "charges_received" value
 * @method string              getSummaryReceived()         Returns the current record's "summary_received" value
 * @method integer             getUserFileId()              Returns the current record's "user_file_id" value
 * @method integer             getStatusId()                Returns the current record's "status_id" value
 * @method UserFile            getUserFile()                Returns the current record's "UserFile" value
 * @method Status              getStatus()                  Returns the current record's "Status" value
 * @method Doctrine_Collection getBriefAdditionalMaterial() Returns the current record's "BriefAdditionalMaterial" collection
 * @method Brief               setRequest1()                Sets the current record's "request1" value
 * @method Brief               setRequest2()                Sets the current record's "request2" value
 * @method Brief               setRequest3()                Sets the current record's "request3" value
 * @method Brief               setRequest4()                Sets the current record's "request4" value
 * @method Brief               setInterviewRecording()      Sets the current record's "interview_recording" value
 * @method Brief               setScanned()                 Sets the current record's "scanned" value
 * @method Brief               setHubScanned()              Sets the current record's "hub_scanned" value
 * @method Brief               setDepositionsAdded()        Sets the current record's "depositions_added" value
 * @method Brief               setRoiTapeReceived()         Sets the current record's "roi_tape_received" value
 * @method Brief               setPhotographsAdded()        Sets the current record's "photographs_added" value
 * @method Brief               setPriorsReceived()          Sets the current record's "priors_received" value
 * @method Brief               setStatementsReceived()      Sets the current record's "statements_received" value
 * @method Brief               setChargesReceived()         Sets the current record's "charges_received" value
 * @method Brief               setSummaryReceived()         Sets the current record's "summary_received" value
 * @method Brief               setUserFileId()              Sets the current record's "user_file_id" value
 * @method Brief               setStatusId()                Sets the current record's "status_id" value
 * @method Brief               setUserFile()                Sets the current record's "UserFile" value
 * @method Brief               setStatus()                  Sets the current record's "Status" value
 * @method Brief               setBriefAdditionalMaterial() Sets the current record's "BriefAdditionalMaterial" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBrief extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('brief');
        $this->hasColumn('request1', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('request2', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('request3', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('request4', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('interview_recording', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('scanned', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('hub_scanned', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('depositions_added', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('roi_tape_received', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('photographs_added', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('priors_received', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('statements_received', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('charges_received', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('summary_received', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Status', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('BriefAdditionalMaterial', array(
             'local' => 'id',
             'foreign' => 'brief_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}