<?php

/**
 * BaseAppeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date_convicted
 * @property date $date_of_sentence
 * @property string $counsel_appearing
 * @property string $client_in_custody
 * @property string $client_to_attend
 * @property string $appear_by_telecourt
 * @property integer $court_convicted_id
 * @property integer $court_date_id
 * @property CourtDate $CourtDate
 * @property Agency $CourtConvicted
 * 
 * @method date      getDateConvicted()       Returns the current record's "date_convicted" value
 * @method date      getDateOfSentence()      Returns the current record's "date_of_sentence" value
 * @method string    getCounselAppearing()    Returns the current record's "counsel_appearing" value
 * @method string    getClientInCustody()     Returns the current record's "client_in_custody" value
 * @method string    getClientToAttend()      Returns the current record's "client_to_attend" value
 * @method string    getAppearByTelecourt()   Returns the current record's "appear_by_telecourt" value
 * @method integer   getCourtConvictedId()    Returns the current record's "court_convicted_id" value
 * @method integer   getCourtDateId()         Returns the current record's "court_date_id" value
 * @method CourtDate getCourtDate()           Returns the current record's "CourtDate" value
 * @method Agency    getCourtConvicted()      Returns the current record's "CourtConvicted" value
 * @method Appeal    setDateConvicted()       Sets the current record's "date_convicted" value
 * @method Appeal    setDateOfSentence()      Sets the current record's "date_of_sentence" value
 * @method Appeal    setCounselAppearing()    Sets the current record's "counsel_appearing" value
 * @method Appeal    setClientInCustody()     Sets the current record's "client_in_custody" value
 * @method Appeal    setClientToAttend()      Sets the current record's "client_to_attend" value
 * @method Appeal    setAppearByTelecourt()   Sets the current record's "appear_by_telecourt" value
 * @method Appeal    setCourtConvictedId()    Sets the current record's "court_convicted_id" value
 * @method Appeal    setCourtDateId()         Sets the current record's "court_date_id" value
 * @method Appeal    setCourtDate()           Sets the current record's "CourtDate" value
 * @method Appeal    setCourtConvicted()      Sets the current record's "CourtConvicted" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppeal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('appeal');
        $this->hasColumn('date_convicted', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_of_sentence', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('counsel_appearing', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('client_in_custody', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('client_to_attend', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('appear_by_telecourt', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('court_convicted_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('court_date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CourtDate', array(
             'local' => 'court_date_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Agency as CourtConvicted', array(
             'local' => 'court_convicted_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}