<?php

/**
 * BaseFeeAgreement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $lump_sum
 * @property decimal $gst
 * @property decimal $total
 * @property decimal $hourly_fee
 * @property decimal $estimate_total
 * @property decimal $counsel_daily_fee
 * @property decimal $instructor_daily_fee
 * @property date $by_what_date
 * @property timestamp $sent_date
 * @property integer $account_type_id
 * @property integer $sent_by_id
 * @property integer $fee_agreement_type_id
 * @property integer $court_date_id
 * @property integer $user_file_id
 * @property AccountType $AccountType
 * @property SentBy $SentBy
 * @property FeeAgreementType $FeeAgreementType
 * @property CourtDate $CourtDate
 * @property UserFile $UserFile
 * 
 * @method decimal          getLumpSum()               Returns the current record's "lump_sum" value
 * @method decimal          getGst()                   Returns the current record's "gst" value
 * @method decimal          getTotal()                 Returns the current record's "total" value
 * @method decimal          getHourlyFee()             Returns the current record's "hourly_fee" value
 * @method decimal          getEstimateTotal()         Returns the current record's "estimate_total" value
 * @method decimal          getCounselDailyFee()       Returns the current record's "counsel_daily_fee" value
 * @method decimal          getInstructorDailyFee()    Returns the current record's "instructor_daily_fee" value
 * @method date             getByWhatDate()            Returns the current record's "by_what_date" value
 * @method timestamp        getSentDate()              Returns the current record's "sent_date" value
 * @method integer          getAccountTypeId()         Returns the current record's "account_type_id" value
 * @method integer          getSentById()              Returns the current record's "sent_by_id" value
 * @method integer          getFeeAgreementTypeId()    Returns the current record's "fee_agreement_type_id" value
 * @method integer          getCourtDateId()           Returns the current record's "court_date_id" value
 * @method integer          getUserFileId()            Returns the current record's "user_file_id" value
 * @method AccountType      getAccountType()           Returns the current record's "AccountType" value
 * @method SentBy           getSentBy()                Returns the current record's "SentBy" value
 * @method FeeAgreementType getFeeAgreementType()      Returns the current record's "FeeAgreementType" value
 * @method CourtDate        getCourtDate()             Returns the current record's "CourtDate" value
 * @method UserFile         getUserFile()              Returns the current record's "UserFile" value
 * @method FeeAgreement     setLumpSum()               Sets the current record's "lump_sum" value
 * @method FeeAgreement     setGst()                   Sets the current record's "gst" value
 * @method FeeAgreement     setTotal()                 Sets the current record's "total" value
 * @method FeeAgreement     setHourlyFee()             Sets the current record's "hourly_fee" value
 * @method FeeAgreement     setEstimateTotal()         Sets the current record's "estimate_total" value
 * @method FeeAgreement     setCounselDailyFee()       Sets the current record's "counsel_daily_fee" value
 * @method FeeAgreement     setInstructorDailyFee()    Sets the current record's "instructor_daily_fee" value
 * @method FeeAgreement     setByWhatDate()            Sets the current record's "by_what_date" value
 * @method FeeAgreement     setSentDate()              Sets the current record's "sent_date" value
 * @method FeeAgreement     setAccountTypeId()         Sets the current record's "account_type_id" value
 * @method FeeAgreement     setSentById()              Sets the current record's "sent_by_id" value
 * @method FeeAgreement     setFeeAgreementTypeId()    Sets the current record's "fee_agreement_type_id" value
 * @method FeeAgreement     setCourtDateId()           Sets the current record's "court_date_id" value
 * @method FeeAgreement     setUserFileId()            Sets the current record's "user_file_id" value
 * @method FeeAgreement     setAccountType()           Sets the current record's "AccountType" value
 * @method FeeAgreement     setSentBy()                Sets the current record's "SentBy" value
 * @method FeeAgreement     setFeeAgreementType()      Sets the current record's "FeeAgreementType" value
 * @method FeeAgreement     setCourtDate()             Sets the current record's "CourtDate" value
 * @method FeeAgreement     setUserFile()              Sets the current record's "UserFile" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeeAgreement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fee_agreement');
        $this->hasColumn('lump_sum', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('gst', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('total', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('hourly_fee', 'decimal', 6, array(
             'type' => 'decimal',
             'length' => 6,
             'scale' => 2,
             ));
        $this->hasColumn('estimate_total', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('counsel_daily_fee', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('instructor_daily_fee', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('by_what_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sent_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('account_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sent_by_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fee_agreement_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('court_date_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AccountType', array(
             'local' => 'account_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('SentBy', array(
             'local' => 'sent_by_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('FeeAgreementType', array(
             'local' => 'fee_agreement_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('CourtDate', array(
             'local' => 'court_date_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}