<?php

/**
 * BaseCustodyVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date
 * @property string $by_who
 * @property boolean $is_by_phone
 * @property string $visit_place
 * @property string $what_discussed
 * @property integer $user_file_id
 * @property UserFile $UserFile
 * 
 * @method timestamp    getDate()           Returns the current record's "date" value
 * @method string       getByWho()          Returns the current record's "by_who" value
 * @method boolean      getIsByPhone()      Returns the current record's "is_by_phone" value
 * @method string       getVisitPlace()     Returns the current record's "visit_place" value
 * @method string       getWhatDiscussed()  Returns the current record's "what_discussed" value
 * @method integer      getUserFileId()     Returns the current record's "user_file_id" value
 * @method UserFile     getUserFile()       Returns the current record's "UserFile" value
 * @method CustodyVisit setDate()           Sets the current record's "date" value
 * @method CustodyVisit setByWho()          Sets the current record's "by_who" value
 * @method CustodyVisit setIsByPhone()      Sets the current record's "is_by_phone" value
 * @method CustodyVisit setVisitPlace()     Sets the current record's "visit_place" value
 * @method CustodyVisit setWhatDiscussed()  Sets the current record's "what_discussed" value
 * @method CustodyVisit setUserFileId()     Sets the current record's "user_file_id" value
 * @method CustodyVisit setUserFile()       Sets the current record's "UserFile" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustodyVisit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('custody_visit');
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('by_who', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('is_by_phone', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('visit_place', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('what_discussed', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}