<?php

/**
 * BaseAidGrant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $aid_in_place
 * @property string $fee_granted
 * @property boolean $is_indictable
 * @property date $date
 * @property integer $legal_aid_id
 * @property LegalAid $LegalAid
 * 
 * @method string   getAidInPlace()    Returns the current record's "aid_in_place" value
 * @method string   getFeeGranted()    Returns the current record's "fee_granted" value
 * @method boolean  getIsIndictable()  Returns the current record's "is_indictable" value
 * @method date     getDate()          Returns the current record's "date" value
 * @method integer  getLegalAidId()    Returns the current record's "legal_aid_id" value
 * @method LegalAid getLegalAid()      Returns the current record's "LegalAid" value
 * @method AidGrant setAidInPlace()    Sets the current record's "aid_in_place" value
 * @method AidGrant setFeeGranted()    Sets the current record's "fee_granted" value
 * @method AidGrant setIsIndictable()  Sets the current record's "is_indictable" value
 * @method AidGrant setDate()          Sets the current record's "date" value
 * @method AidGrant setLegalAidId()    Sets the current record's "legal_aid_id" value
 * @method AidGrant setLegalAid()      Sets the current record's "LegalAid" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAidGrant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aid_grant');
        $this->hasColumn('aid_in_place', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('fee_granted', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('is_indictable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('legal_aid_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LegalAid', array(
             'local' => 'legal_aid_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}