<?php

/**
 * BaseSubgroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $short_name
 * @property boolean $is_active
 * @property integer $group_id
 * @property sfGuardGroup $Group
 * @property Doctrine_Collection $Agency
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getShortName()  Returns the current record's "short_name" value
 * @method boolean             getIsActive()   Returns the current record's "is_active" value
 * @method integer             getGroupId()    Returns the current record's "group_id" value
 * @method sfGuardGroup        getGroup()      Returns the current record's "Group" value
 * @method Doctrine_Collection getAgency()     Returns the current record's "Agency" collection
 * @method Subgroup            setName()       Sets the current record's "name" value
 * @method Subgroup            setShortName()  Sets the current record's "short_name" value
 * @method Subgroup            setIsActive()   Sets the current record's "is_active" value
 * @method Subgroup            setGroupId()    Sets the current record's "group_id" value
 * @method Subgroup            setGroup()      Sets the current record's "Group" value
 * @method Subgroup            setAgency()     Sets the current record's "Agency" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubgroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subgroup');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('short_name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Agency', array(
             'local' => 'id',
             'foreign' => 'subgroup_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}