<?php

/**
 * BaseAgency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $reference_number
 * @property string $street
 * @property string $suburb
 * @property string $postcode
 * @property string $city
 * @property string $state
 * @property string $phone
 * @property string $general_phone
 * @property string $fax
 * @property string $general_fax
 * @property string $email
 * @property string $website
 * @property string $logo_file
 * @property integer $sf_guard_group_id
 * @property integer $subgroup_id
 * @property integer $status_id
 * @property sfGuardGroup $Group
 * @property Subgroup $Subgroup
 * @property Status $Status
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $sfGuardUserAgency
 * @property Doctrine_Collection $Appeal
 * @property Doctrine_Collection $CourtDate
 * @property Doctrine_Collection $OfficeLegalAids
 * @property Doctrine_Collection $ProsecutionUserFiles
 * @property Doctrine_Collection $PrisonUserFiles
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getReferenceNumber()      Returns the current record's "reference_number" value
 * @method string              getStreet()               Returns the current record's "street" value
 * @method string              getSuburb()               Returns the current record's "suburb" value
 * @method string              getPostcode()             Returns the current record's "postcode" value
 * @method string              getCity()                 Returns the current record's "city" value
 * @method string              getState()                Returns the current record's "state" value
 * @method string              getPhone()                Returns the current record's "phone" value
 * @method string              getGeneralPhone()         Returns the current record's "general_phone" value
 * @method string              getFax()                  Returns the current record's "fax" value
 * @method string              getGeneralFax()           Returns the current record's "general_fax" value
 * @method string              getEmail()                Returns the current record's "email" value
 * @method string              getWebsite()              Returns the current record's "website" value
 * @method string              getLogoFile()             Returns the current record's "logo_file" value
 * @method integer             getSfGuardGroupId()       Returns the current record's "sf_guard_group_id" value
 * @method integer             getSubgroupId()           Returns the current record's "subgroup_id" value
 * @method integer             getStatusId()             Returns the current record's "status_id" value
 * @method sfGuardGroup        getGroup()                Returns the current record's "Group" value
 * @method Subgroup            getSubgroup()             Returns the current record's "Subgroup" value
 * @method Status              getStatus()               Returns the current record's "Status" value
 * @method Doctrine_Collection getUsers()                Returns the current record's "Users" collection
 * @method Doctrine_Collection getSfGuardUserAgency()    Returns the current record's "sfGuardUserAgency" collection
 * @method Doctrine_Collection getAppeal()               Returns the current record's "Appeal" collection
 * @method Doctrine_Collection getCourtDate()            Returns the current record's "CourtDate" collection
 * @method Doctrine_Collection getOfficeLegalAids()      Returns the current record's "OfficeLegalAids" collection
 * @method Doctrine_Collection getProsecutionUserFiles() Returns the current record's "ProsecutionUserFiles" collection
 * @method Doctrine_Collection getPrisonUserFiles()      Returns the current record's "PrisonUserFiles" collection
 * @method Agency              setName()                 Sets the current record's "name" value
 * @method Agency              setReferenceNumber()      Sets the current record's "reference_number" value
 * @method Agency              setStreet()               Sets the current record's "street" value
 * @method Agency              setSuburb()               Sets the current record's "suburb" value
 * @method Agency              setPostcode()             Sets the current record's "postcode" value
 * @method Agency              setCity()                 Sets the current record's "city" value
 * @method Agency              setState()                Sets the current record's "state" value
 * @method Agency              setPhone()                Sets the current record's "phone" value
 * @method Agency              setGeneralPhone()         Sets the current record's "general_phone" value
 * @method Agency              setFax()                  Sets the current record's "fax" value
 * @method Agency              setGeneralFax()           Sets the current record's "general_fax" value
 * @method Agency              setEmail()                Sets the current record's "email" value
 * @method Agency              setWebsite()              Sets the current record's "website" value
 * @method Agency              setLogoFile()             Sets the current record's "logo_file" value
 * @method Agency              setSfGuardGroupId()       Sets the current record's "sf_guard_group_id" value
 * @method Agency              setSubgroupId()           Sets the current record's "subgroup_id" value
 * @method Agency              setStatusId()             Sets the current record's "status_id" value
 * @method Agency              setGroup()                Sets the current record's "Group" value
 * @method Agency              setSubgroup()             Sets the current record's "Subgroup" value
 * @method Agency              setStatus()               Sets the current record's "Status" value
 * @method Agency              setUsers()                Sets the current record's "Users" collection
 * @method Agency              setSfGuardUserAgency()    Sets the current record's "sfGuardUserAgency" collection
 * @method Agency              setAppeal()               Sets the current record's "Appeal" collection
 * @method Agency              setCourtDate()            Sets the current record's "CourtDate" collection
 * @method Agency              setOfficeLegalAids()      Sets the current record's "OfficeLegalAids" collection
 * @method Agency              setProsecutionUserFiles() Sets the current record's "ProsecutionUserFiles" collection
 * @method Agency              setPrisonUserFiles()      Sets the current record's "PrisonUserFiles" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agency');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('reference_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('street', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('suburb', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('postcode', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('city', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('state', 'string', 120, array(
             'type' => 'string',
             'default' => 'VIC',
             'length' => 120,
             ));
        $this->hasColumn('phone', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('general_phone', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('fax', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('general_fax', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('email', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('website', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('logo_file', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('sf_guard_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('subgroup_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('name_idx', array(
             'fields' => 'name',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'sf_guard_group_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Subgroup', array(
             'local' => 'subgroup_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Status', array(
             'local' => 'status_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserAgency',
             'local' => 'agency_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserAgency', array(
             'local' => 'id',
             'foreign' => 'agency_id'));

        $this->hasMany('Appeal', array(
             'local' => 'id',
             'foreign' => 'court_convicted_id'));

        $this->hasMany('CourtDate', array(
             'local' => 'id',
             'foreign' => 'court_id'));

        $this->hasMany('LegalAid as OfficeLegalAids', array(
             'local' => 'id',
             'foreign' => 'office_id'));

        $this->hasMany('UserFile as ProsecutionUserFiles', array(
             'local' => 'id',
             'foreign' => 'prosecution_id'));

        $this->hasMany('UserFile as PrisonUserFiles', array(
             'local' => 'id',
             'foreign' => 'prison_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}