<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $status_type_id
 * @property StatusType $StatusType
 * @property Doctrine_Collection $Agency
 * @property Doctrine_Collection $Brief
 * @property Doctrine_Collection $BriefStatusCommittalStreams
 * @property Doctrine_Collection $Fee
 * @property Doctrine_Collection $Invoice
 * @property Doctrine_Collection $VlaLegalAids
 * @property Doctrine_Collection $AidLegalAids
 * @property Doctrine_Collection $Receipt
 * @property Doctrine_Collection $UserFile
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getDescription()                 Returns the current record's "description" value
 * @method integer             getStatusTypeId()                Returns the current record's "status_type_id" value
 * @method StatusType          getStatusType()                  Returns the current record's "StatusType" value
 * @method Doctrine_Collection getAgency()                      Returns the current record's "Agency" collection
 * @method Doctrine_Collection getBrief()                       Returns the current record's "Brief" collection
 * @method Doctrine_Collection getBriefStatusCommittalStreams() Returns the current record's "BriefStatusCommittalStreams" collection
 * @method Doctrine_Collection getFee()                         Returns the current record's "Fee" collection
 * @method Doctrine_Collection getInvoice()                     Returns the current record's "Invoice" collection
 * @method Doctrine_Collection getVlaLegalAids()                Returns the current record's "VlaLegalAids" collection
 * @method Doctrine_Collection getAidLegalAids()                Returns the current record's "AidLegalAids" collection
 * @method Doctrine_Collection getReceipt()                     Returns the current record's "Receipt" collection
 * @method Doctrine_Collection getUserFile()                    Returns the current record's "UserFile" collection
 * @method Status              setName()                        Sets the current record's "name" value
 * @method Status              setDescription()                 Sets the current record's "description" value
 * @method Status              setStatusTypeId()                Sets the current record's "status_type_id" value
 * @method Status              setStatusType()                  Sets the current record's "StatusType" value
 * @method Status              setAgency()                      Sets the current record's "Agency" collection
 * @method Status              setBrief()                       Sets the current record's "Brief" collection
 * @method Status              setBriefStatusCommittalStreams() Sets the current record's "BriefStatusCommittalStreams" collection
 * @method Status              setFee()                         Sets the current record's "Fee" collection
 * @method Status              setInvoice()                     Sets the current record's "Invoice" collection
 * @method Status              setVlaLegalAids()                Sets the current record's "VlaLegalAids" collection
 * @method Status              setAidLegalAids()                Sets the current record's "AidLegalAids" collection
 * @method Status              setReceipt()                     Sets the current record's "Receipt" collection
 * @method Status              setUserFile()                    Sets the current record's "UserFile" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('StatusType', array(
             'local' => 'status_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Agency', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('Brief', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('CommittalStream as BriefStatusCommittalStreams', array(
             'local' => 'id',
             'foreign' => 'brief_status_id'));

        $this->hasMany('Fee', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('Invoice', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('LegalAid as VlaLegalAids', array(
             'local' => 'id',
             'foreign' => 'vla_app_status_id'));

        $this->hasMany('LegalAid as AidLegalAids', array(
             'local' => 'id',
             'foreign' => 'aid_status_id'));

        $this->hasMany('Receipt', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasMany('UserFile', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}