<?php

/**
 * BaseDocumentTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $is_active
 * @property string $template_file
 * @property string $template_word_file
 * @property string $field1_params
 * @property string $field2_params
 * @property string $field3_params
 * @property string $field4_params
 * @property string $field5_params
 * @property string $field6_params
 * @property string $field7_params
 * @property string $field8_params
 * @property string $field9_params
 * @property string $field10_params
 * @property string $field11_params
 * @property string $field12_params
 * @property string $field13_params
 * @property string $field14_params
 * @property string $field15_params
 * @property string $field16_params
 * @property string $field17_params
 * @property string $field18_params
 * @property string $field19_params
 * @property string $field20_params
 * @property integer $document_type_id
 * @property integer $admin_section_id
 * @property DocumentType $DocumentType
 * @property AdminSection $AdminSection
 * @property Doctrine_Collection $Document
 * @property Doctrine_Collection $DocumentDetail
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method string              getTemplateFile()       Returns the current record's "template_file" value
 * @method string              getTemplateWordFile()   Returns the current record's "template_word_file" value
 * @method string              getField1Params()       Returns the current record's "field1_params" value
 * @method string              getField2Params()       Returns the current record's "field2_params" value
 * @method string              getField3Params()       Returns the current record's "field3_params" value
 * @method string              getField4Params()       Returns the current record's "field4_params" value
 * @method string              getField5Params()       Returns the current record's "field5_params" value
 * @method string              getField6Params()       Returns the current record's "field6_params" value
 * @method string              getField7Params()       Returns the current record's "field7_params" value
 * @method string              getField8Params()       Returns the current record's "field8_params" value
 * @method string              getField9Params()       Returns the current record's "field9_params" value
 * @method string              getField10Params()      Returns the current record's "field10_params" value
 * @method string              getField11Params()      Returns the current record's "field11_params" value
 * @method string              getField12Params()      Returns the current record's "field12_params" value
 * @method string              getField13Params()      Returns the current record's "field13_params" value
 * @method string              getField14Params()      Returns the current record's "field14_params" value
 * @method string              getField15Params()      Returns the current record's "field15_params" value
 * @method string              getField16Params()      Returns the current record's "field16_params" value
 * @method string              getField17Params()      Returns the current record's "field17_params" value
 * @method string              getField18Params()      Returns the current record's "field18_params" value
 * @method string              getField19Params()      Returns the current record's "field19_params" value
 * @method string              getField20Params()      Returns the current record's "field20_params" value
 * @method integer             getDocumentTypeId()     Returns the current record's "document_type_id" value
 * @method integer             getAdminSectionId()     Returns the current record's "admin_section_id" value
 * @method DocumentType        getDocumentType()       Returns the current record's "DocumentType" value
 * @method AdminSection        getAdminSection()       Returns the current record's "AdminSection" value
 * @method Doctrine_Collection getDocument()           Returns the current record's "Document" collection
 * @method Doctrine_Collection getDocumentDetail()     Returns the current record's "DocumentDetail" collection
 * @method DocumentTemplate    setName()               Sets the current record's "name" value
 * @method DocumentTemplate    setIsActive()           Sets the current record's "is_active" value
 * @method DocumentTemplate    setTemplateFile()       Sets the current record's "template_file" value
 * @method DocumentTemplate    setTemplateWordFile()   Sets the current record's "template_word_file" value
 * @method DocumentTemplate    setField1Params()       Sets the current record's "field1_params" value
 * @method DocumentTemplate    setField2Params()       Sets the current record's "field2_params" value
 * @method DocumentTemplate    setField3Params()       Sets the current record's "field3_params" value
 * @method DocumentTemplate    setField4Params()       Sets the current record's "field4_params" value
 * @method DocumentTemplate    setField5Params()       Sets the current record's "field5_params" value
 * @method DocumentTemplate    setField6Params()       Sets the current record's "field6_params" value
 * @method DocumentTemplate    setField7Params()       Sets the current record's "field7_params" value
 * @method DocumentTemplate    setField8Params()       Sets the current record's "field8_params" value
 * @method DocumentTemplate    setField9Params()       Sets the current record's "field9_params" value
 * @method DocumentTemplate    setField10Params()      Sets the current record's "field10_params" value
 * @method DocumentTemplate    setField11Params()      Sets the current record's "field11_params" value
 * @method DocumentTemplate    setField12Params()      Sets the current record's "field12_params" value
 * @method DocumentTemplate    setField13Params()      Sets the current record's "field13_params" value
 * @method DocumentTemplate    setField14Params()      Sets the current record's "field14_params" value
 * @method DocumentTemplate    setField15Params()      Sets the current record's "field15_params" value
 * @method DocumentTemplate    setField16Params()      Sets the current record's "field16_params" value
 * @method DocumentTemplate    setField17Params()      Sets the current record's "field17_params" value
 * @method DocumentTemplate    setField18Params()      Sets the current record's "field18_params" value
 * @method DocumentTemplate    setField19Params()      Sets the current record's "field19_params" value
 * @method DocumentTemplate    setField20Params()      Sets the current record's "field20_params" value
 * @method DocumentTemplate    setDocumentTypeId()     Sets the current record's "document_type_id" value
 * @method DocumentTemplate    setAdminSectionId()     Sets the current record's "admin_section_id" value
 * @method DocumentTemplate    setDocumentType()       Sets the current record's "DocumentType" value
 * @method DocumentTemplate    setAdminSection()       Sets the current record's "AdminSection" value
 * @method DocumentTemplate    setDocument()           Sets the current record's "Document" collection
 * @method DocumentTemplate    setDocumentDetail()     Sets the current record's "DocumentDetail" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_template');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('template_file', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('template_word_file', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('field1_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field2_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field3_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field4_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field5_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field6_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field7_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field8_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field9_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field10_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field11_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field12_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field13_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field14_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field15_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field16_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field17_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field18_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field19_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('field20_params', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('document_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('admin_section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DocumentType', array(
             'local' => 'document_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('AdminSection', array(
             'local' => 'admin_section_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Document', array(
             'local' => 'id',
             'foreign' => 'document_template_id'));

        $this->hasMany('DocumentDetail', array(
             'local' => 'id',
             'foreign' => 'document_template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}