<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $street
 * @property string $suburb
 * @property string $postcode
 * @property string $city
 * @property string $state
 * @property string $home_phone
 * @property string $work_phone
 * @property string $mobile
 * @property string $other_phone
 * @property string $fax
 * @property date $dob
 * @property string $picture_file
 * @property string $badge_number
 * @property string $signature_file
 * @property string $criminal_crn
 * @property string $centrelink_crn
 * @property date $hcc_expiration_date
 * @property integer $referral_id
 * @property integer $user_id
 * @property integer $related_user_id
 * @property integer $preferred_contact_id
 * @property integer $honorific_id
 * @property Referral $Referral
 * @property sfGuardUser $User
 * @property sfGuardUser $RelatedUser
 * @property PreferredContact $PreferredContact
 * @property Honorific $Honorific
 * 
 * @method string             getStreet()               Returns the current record's "street" value
 * @method string             getSuburb()               Returns the current record's "suburb" value
 * @method string             getPostcode()             Returns the current record's "postcode" value
 * @method string             getCity()                 Returns the current record's "city" value
 * @method string             getState()                Returns the current record's "state" value
 * @method string             getHomePhone()            Returns the current record's "home_phone" value
 * @method string             getWorkPhone()            Returns the current record's "work_phone" value
 * @method string             getMobile()               Returns the current record's "mobile" value
 * @method string             getOtherPhone()           Returns the current record's "other_phone" value
 * @method string             getFax()                  Returns the current record's "fax" value
 * @method date               getDob()                  Returns the current record's "dob" value
 * @method string             getPictureFile()          Returns the current record's "picture_file" value
 * @method string             getBadgeNumber()          Returns the current record's "badge_number" value
 * @method string             getSignatureFile()        Returns the current record's "signature_file" value
 * @method string             getCriminalCrn()          Returns the current record's "criminal_crn" value
 * @method string             getCentrelinkCrn()        Returns the current record's "centrelink_crn" value
 * @method date               getHccExpirationDate()    Returns the current record's "hcc_expiration_date" value
 * @method integer            getReferralId()           Returns the current record's "referral_id" value
 * @method integer            getUserId()               Returns the current record's "user_id" value
 * @method integer            getRelatedUserId()        Returns the current record's "related_user_id" value
 * @method integer            getPreferredContactId()   Returns the current record's "preferred_contact_id" value
 * @method integer            getHonorificId()          Returns the current record's "honorific_id" value
 * @method Referral           getReferral()             Returns the current record's "Referral" value
 * @method sfGuardUser        getUser()                 Returns the current record's "User" value
 * @method sfGuardUser        getRelatedUser()          Returns the current record's "RelatedUser" value
 * @method PreferredContact   getPreferredContact()     Returns the current record's "PreferredContact" value
 * @method Honorific          getHonorific()            Returns the current record's "Honorific" value
 * @method sfGuardUserProfile setStreet()               Sets the current record's "street" value
 * @method sfGuardUserProfile setSuburb()               Sets the current record's "suburb" value
 * @method sfGuardUserProfile setPostcode()             Sets the current record's "postcode" value
 * @method sfGuardUserProfile setCity()                 Sets the current record's "city" value
 * @method sfGuardUserProfile setState()                Sets the current record's "state" value
 * @method sfGuardUserProfile setHomePhone()            Sets the current record's "home_phone" value
 * @method sfGuardUserProfile setWorkPhone()            Sets the current record's "work_phone" value
 * @method sfGuardUserProfile setMobile()               Sets the current record's "mobile" value
 * @method sfGuardUserProfile setOtherPhone()           Sets the current record's "other_phone" value
 * @method sfGuardUserProfile setFax()                  Sets the current record's "fax" value
 * @method sfGuardUserProfile setDob()                  Sets the current record's "dob" value
 * @method sfGuardUserProfile setPictureFile()          Sets the current record's "picture_file" value
 * @method sfGuardUserProfile setBadgeNumber()          Sets the current record's "badge_number" value
 * @method sfGuardUserProfile setSignatureFile()        Sets the current record's "signature_file" value
 * @method sfGuardUserProfile setCriminalCrn()          Sets the current record's "criminal_crn" value
 * @method sfGuardUserProfile setCentrelinkCrn()        Sets the current record's "centrelink_crn" value
 * @method sfGuardUserProfile setHccExpirationDate()    Sets the current record's "hcc_expiration_date" value
 * @method sfGuardUserProfile setReferralId()           Sets the current record's "referral_id" value
 * @method sfGuardUserProfile setUserId()               Sets the current record's "user_id" value
 * @method sfGuardUserProfile setRelatedUserId()        Sets the current record's "related_user_id" value
 * @method sfGuardUserProfile setPreferredContactId()   Sets the current record's "preferred_contact_id" value
 * @method sfGuardUserProfile setHonorificId()          Sets the current record's "honorific_id" value
 * @method sfGuardUserProfile setReferral()             Sets the current record's "Referral" value
 * @method sfGuardUserProfile setUser()                 Sets the current record's "User" value
 * @method sfGuardUserProfile setRelatedUser()          Sets the current record's "RelatedUser" value
 * @method sfGuardUserProfile setPreferredContact()     Sets the current record's "PreferredContact" value
 * @method sfGuardUserProfile setHonorific()            Sets the current record's "Honorific" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('street', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('suburb', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('postcode', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('city', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('state', 'string', 30, array(
             'type' => 'string',
             'default' => 'VIC',
             'length' => 30,
             ));
        $this->hasColumn('home_phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('work_phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mobile', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('other_phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fax', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dob', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('picture_file', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('badge_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('signature_file', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('criminal_crn', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('centrelink_crn', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('hcc_expiration_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('referral_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('related_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('preferred_contact_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('honorific_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('criminal_crn_idx', array(
             'fields' => 'criminal_crn',
             ));
        $this->index('centrelink_crn_idx', array(
             'fields' => 'centrelink_crn',
             ));
        $this->index('badge_number_idx', array(
             'fields' => 'badge_number',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Referral', array(
             'local' => 'referral_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as RelatedUser', array(
             'local' => 'related_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('PreferredContact', array(
             'local' => 'preferred_contact_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Honorific', array(
             'local' => 'honorific_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}