<?php

/**
 * BaseReferral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * @property date $first_thanked_date
 * @property date $current_thanked_date
 * @property integer $thanked_times
 * @property Doctrine_Collection $sfGuardUserProfile
 * 
 * @method string              getValue()                Returns the current record's "value" value
 * @method date                getFirstThankedDate()     Returns the current record's "first_thanked_date" value
 * @method date                getCurrentThankedDate()   Returns the current record's "current_thanked_date" value
 * @method integer             getThankedTimes()         Returns the current record's "thanked_times" value
 * @method Doctrine_Collection getSfGuardUserProfile()   Returns the current record's "sfGuardUserProfile" collection
 * @method Referral            setValue()                Sets the current record's "value" value
 * @method Referral            setFirstThankedDate()     Sets the current record's "first_thanked_date" value
 * @method Referral            setCurrentThankedDate()   Sets the current record's "current_thanked_date" value
 * @method Referral            setThankedTimes()         Sets the current record's "thanked_times" value
 * @method Referral            setSfGuardUserProfile()   Sets the current record's "sfGuardUserProfile" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReferral extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('referral');
        $this->hasColumn('value', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('first_thanked_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('current_thanked_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('thanked_times', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'referral_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}