<?php

/**
 * BaseAdminContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $value
 * @property boolean $is_active
 * @property string $type
 * @property string $format_params
 * @property integer $document_type_id
 * @property integer $admin_section_id
 * @property DocumentType $DocumentType
 * @property AdminSection $AdminSection
 * 
 * @method string       getCode()             Returns the current record's "code" value
 * @method string       getValue()            Returns the current record's "value" value
 * @method boolean      getIsActive()         Returns the current record's "is_active" value
 * @method string       getType()             Returns the current record's "type" value
 * @method string       getFormatParams()     Returns the current record's "format_params" value
 * @method integer      getDocumentTypeId()   Returns the current record's "document_type_id" value
 * @method integer      getAdminSectionId()   Returns the current record's "admin_section_id" value
 * @method DocumentType getDocumentType()     Returns the current record's "DocumentType" value
 * @method AdminSection getAdminSection()     Returns the current record's "AdminSection" value
 * @method AdminContent setCode()             Sets the current record's "code" value
 * @method AdminContent setValue()            Sets the current record's "value" value
 * @method AdminContent setIsActive()         Sets the current record's "is_active" value
 * @method AdminContent setType()             Sets the current record's "type" value
 * @method AdminContent setFormatParams()     Sets the current record's "format_params" value
 * @method AdminContent setDocumentTypeId()   Sets the current record's "document_type_id" value
 * @method AdminContent setAdminSectionId()   Sets the current record's "admin_section_id" value
 * @method AdminContent setDocumentType()     Sets the current record's "DocumentType" value
 * @method AdminContent setAdminSection()     Sets the current record's "AdminSection" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdminContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_content');
        $this->hasColumn('code', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('value', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('type', 'string', 10, array(
             'type' => 'string',
             'default' => 'FIXED',
             'length' => 10,
             ));
        $this->hasColumn('format_params', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('document_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('admin_section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DocumentType', array(
             'local' => 'document_type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('AdminSection', array(
             'local' => 'admin_section_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}