<?php

/**
 * BaseBriefAdditionalMaterial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property date $date
 * @property integer $brief_id
 * @property Brief $Brief
 * 
 * @method string                  getDescription() Returns the current record's "description" value
 * @method date                    getDate()        Returns the current record's "date" value
 * @method integer                 getBriefId()     Returns the current record's "brief_id" value
 * @method Brief                   getBrief()       Returns the current record's "Brief" value
 * @method BriefAdditionalMaterial setDescription() Sets the current record's "description" value
 * @method BriefAdditionalMaterial setDate()        Sets the current record's "date" value
 * @method BriefAdditionalMaterial setBriefId()     Sets the current record's "brief_id" value
 * @method BriefAdditionalMaterial setBrief()       Sets the current record's "Brief" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBriefAdditionalMaterial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('brief_additional_material');
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('brief_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Brief', array(
             'local' => 'brief_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}