<?php

/**
 * BaseShortMessageTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $message
 * @property boolean $is_active
 * 
 * @method string               getName()      Returns the current record's "name" value
 * @method string               getMessage()   Returns the current record's "message" value
 * @method boolean              getIsActive()  Returns the current record's "is_active" value
 * @method ShortMessageTemplate setName()      Sets the current record's "name" value
 * @method ShortMessageTemplate setMessage()   Sets the current record's "message" value
 * @method ShortMessageTemplate setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShortMessageTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('short_message_template');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}