<?php

/**
 * BaseCharge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $item
 * @property string $section
 * @property string $acts
 * @property string $charge
 * @property string $comment
 * @property date $date
 * @property integer $user_file_id
 * @property integer $type_id
 * @property UserFile $UserFile
 * @property ChargeType $ChargeType
 * 
 * @method string     getItem()         Returns the current record's "item" value
 * @method string     getSection()      Returns the current record's "section" value
 * @method string     getActs()         Returns the current record's "acts" value
 * @method string     getCharge()       Returns the current record's "charge" value
 * @method string     getComment()      Returns the current record's "comment" value
 * @method date       getDate()         Returns the current record's "date" value
 * @method integer    getUserFileId()   Returns the current record's "user_file_id" value
 * @method integer    getTypeId()       Returns the current record's "type_id" value
 * @method UserFile   getUserFile()     Returns the current record's "UserFile" value
 * @method ChargeType getChargeType()   Returns the current record's "ChargeType" value
 * @method Charge     setItem()         Sets the current record's "item" value
 * @method Charge     setSection()      Sets the current record's "section" value
 * @method Charge     setActs()         Sets the current record's "acts" value
 * @method Charge     setCharge()       Sets the current record's "charge" value
 * @method Charge     setComment()      Sets the current record's "comment" value
 * @method Charge     setDate()         Sets the current record's "date" value
 * @method Charge     setUserFileId()   Sets the current record's "user_file_id" value
 * @method Charge     setTypeId()       Sets the current record's "type_id" value
 * @method Charge     setUserFile()     Sets the current record's "UserFile" value
 * @method Charge     setChargeType()   Sets the current record's "ChargeType" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCharge extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('charge');
        $this->hasColumn('item', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('section', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('acts', 'string', 120, array(
             'type' => 'string',
             'length' => 120,
             ));
        $this->hasColumn('charge', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('user_file_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('charge_idx', array(
             'fields' => 'charge',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserFile', array(
             'local' => 'user_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChargeType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}