generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Agency
    theme:                 zafire
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          agency
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 1
        #table_method: getCriminalTrialListingDirectorate
      filter:  ~
      form:
      edit:
        actions: 
          _save:
          search_mode:
        #return_to: edit
      ajaxedit: ~
      new:  
        actions: 
          _save:
          search_mode:
        #return_to: edit
      show:    ~
      
