generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Invoice
    theme:                 zafire
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          invoice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [number, date, _details, _documents, updated_at]
        max_per_page: 20
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    
        title: Edit Invoice Number %%number%%
        actions: 
          _save:
          _list:
          #return_to: edit
      ajaxedit: ~
      new:     
        actions: 
          _save:
          _list:
          #return_to: edit
      show:    ~
      
