<?php

/**
 * AdminContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminContent');
    }
}