<?php

/**
 * AdminContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdminContent extends BaseAdminContent
{
  public static function getContent($doc_type_id, $field)
  {
    $content = null;
    if ($doc_type_id) {
      $content = Doctrine::getTable('AdminContent')->createQuery()
                //->select('value, format_params')
                ->where('code = ? AND document_type_id = ? AND is_active = ?', array($field, $doc_type_id, 1))
                ->orderBy('updated_at DESC')
                ->limit(1)
                ->fetchOne();
    }
    return $content;
  }
  
  public static function getText($dtsn, $field='document_field17')
  {
    $text = '';
    
    $doc_type = Doctrine::getTable('DocumentType')->findOneBy('short_name', $dtsn);
    $doc_type_id = ($doc_type) ? $doc_type->getId() : null;
    $content = self::getContent($doc_type_id, $field);
    
    if ($content) {
      $text = $content->getValue();
      if ($text == '') {
        $content = self::getParentContent($doc_type_id, $field, $content);
        if ($content) $text = $content->getValue();
      }
    }
    return $text;
  }
  
  
  public static function getParentContent($doc_type_id, $field, $content)
  {
    $format_params = @json_decode(trim($content->getFormatParams()), true);
    if ($format_params && isset($format_params['parent'])) {
      $doc_type = Doctrine::getTable('DocumentType')->find((int)$format_params['parent']);
      $doc_type_id = ($doc_type) ? $doc_type->getId() : null;
      $contentp = self::getContent($doc_type_id, $field);
      if ($contentp) $content = $contentp;
    }
    return $content;
  }
  
  
  public static function saveText($dtsn, $request)
  {
    $field = ($request->getParameter('id')) ? $request->getParameter('id') : null;
    $new_value = ($request->getParameter('value')) ? $request->getParameter('value') : null;
    $type = ($request->getParameter('type')) ? $request->getParameter('type') : 'FIXED';
  
    $doc_type_id = null;
    if ($dtsn != 'empty') {
      $doc_type_obj = Doctrine::getTable('DocumentType')->findOneBy('short_name', $dtsn);
      if ($doc_type_obj) $doc_type_id = $doc_type_obj->getId();
    }
    
    $result_msg = 'Error: No valid dcoument or text element!';
    if ($field && $doc_type_id) {
      $content = self::getContent($doc_type_id, $field);
      if (empty($content)) {
        $content = new AdminContent();
        $content->setCode($field);
        $content->setDocumentTypeId($doc_type_id);
        $content->setType($type);
      }
      else if ($content->getValue() == '') { // seek for parent content to update all the family
        $content = self::getParentContent($doc_type_id, $field, $content);
      }
      $content->setValue($new_value);
      $content->setUpdatedAt(date('Y-m-d H:i:s'));
      $content->save();
      $result_msg = 'Text has been saved successfully!'; //.$doc_type_id.'-'.$elem_id;
    }
    
    return $result_msg;
  }

}