<?php

/**
 * AdminSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminSectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminSection');
    }
}