<?php

/**
 * Agency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agency extends BaseAgency
{
  public function obtainClientId($module_name)
  {
    $client = sfContext::getInstance()->getUser()->getAttribute('client', null);  
    return ($client) ? $client['id'] : null;
  }
  
  public function obtainUserFileId($module_name)
  {
    $client = sfContext::getInstance()->getUser()->getAttribute('client', null);
    return (($client) && (isset($client['last_file_id']))) ? $client['last_file_id'] : null;
  }
  
  public function getGroupName()
  {
    return $this->getGroup()->getName();
  }
  
  public function getSubGroupName()
  {
    return $this->getSubgroup()->getName();
  }
  
  public function retrieveUserByGroup($field, $value)
  {
    $user_id = '';
    $belongs = false;
    foreach ($this->sfGuardUserAgency as $user_obj) {
      if (Doctrine::getTable('sfGuardUser')->userBelongsGroup($user_obj->getUserId(), $field, $value)) {
        $user_id = $user_obj->getUserId();
        $belongs = true;
        break;
      }     
    }
    return $user_id;
  }
  
  public function getFullAddress($with_name=null, $with_contact=null)
  {
    if ($with_name) $address_arr[] = trim($this->getName());
    
    $address_arr0[] = trim($this->getStreet());
    $address_arr0[] = trim($this->getSuburb());
    $address_arr[] = implode("\n", array_filter($address_arr0));
    if ($address_arr[sizeof($address_arr)-1]) $address_arr[] = trim($this->getState()." ".$this->getPostcode());
    
    if ($with_contact) $address_arr[] = trim($this->getContactData());
    
    $full_address = implode("\n", array_filter($address_arr));
    
    return $full_address;
  }
  
  public function getContactData($option='p&f')
  {
    $phones_arr = array('phone' => trim($this->getPhone()),         'fax' => trim($this->getFax()));
    $gphones_arr = array('phone' => trim($this->getGeneralPhone()), 'fax' => trim($this->getGeneralFax()));
    
    foreach ($phones_arr as $type => $phone) {
      if ($phone != '') $contact_info_arr[] = ucfirst($type).": ".$phone; 
      else $contact_info_arr[] = ($gphones_arr[$type] != '') ? ucfirst($type).": ".$gphones_arr[$type] : "";
    }
    if ($option == 'all') $contact_info_arr[] = (trim($this->getEmail()) != '') ? "Email: ".trim($this->getEmail()) : "";
    
    $contact_info = implode("\n", array_filter($contact_info_arr));
    
    return $contact_info;
  }
  
  // added by William, 16/05/2013: override method to customize name
  public function getName()
  {
    $name = $this->_get('name');
    if (sfContext::getInstance()->getModuleName() == 'document') {
      $name = trim($name);
      if (strpos(strtolower($name), 'melbourne magistrates') !== false) {
        $arr = explode(' ', $name);
        if (isset($arr[3])) unset($arr[3]);
        $name = implode(' ', $arr);
      }
    }
    return $name;
  }      
  
}