<?php

/**
 * AgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgencyTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object AgencyTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Agency');
  }
    
  // to load the agency lists by group
  public function getAgenciesByGroup($q, $code)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Group gg')
    ->andWhere('gg.code=?', $code);
    return $q;    
  }
  
  public function getProsecutions(Doctrine_Query $q)    { return $this->getAgenciesByGroup($q, 'PRS'); }
  
  public function getCTLDirectorates(Doctrine_Query $q) { return $this->getAgenciesByGroup($q, 'CLD'); }
  
  public function getPrisons(Doctrine_Query $q)         { return $this->getAgenciesByGroup($q, 'PRI'); }
  
  
  // to load agency combo boxes values by group
  public function getAgenciesByGroupCB($code)
  {
    $q = $this->createQuery('ag');
    $q->leftJoin('ag.Group gg')
    ->andWhere('gg.code=?', $code)
    ->orderBy('ag.name ASC');   // always sort by name
    return $q;
  }
  
  public function getVLAOfficesCB()       { return $this->getAgenciesByGroupCB('VLA'); }
  
  public function getProsecutionsCB()     { return $this->getAgenciesByGroupCB('PRS'); }
  
  public function getPrisonsCB()          { return $this->getAgenciesByGroupCB('PRI'); }
  
  public function getPoliceStationsCB()   { return $this->getAgenciesByGroupCB('POL'); }
  
  public function getCourtsCB()           { return $this->getAgenciesByGroupCB('COU'); }
  
  public function getClerkOfficesCB()     { return $this->getAgenciesByGroupCB('CLO'); }
  
  
  function retrieveAgenciesForSelect($search_str, $limit, $code=null)
  {
    $q = ($code) ? $this->getAgenciesByGroupCB($code) : $this->createQuery('ag');
    $q->andWhere('(ag.name LIKE "%'.$search_str.'%")')
        ->addOrderBy('ag.name')
        ->limit($limit);

    $agencies = array();
    foreach ($q->execute() as $agency) {
      $agencies[$agency->getId()] = $agency->getName();
    }
    return $agencies;
  }
  
  
  public function mainFilter(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    
    // to filter by Group according to the module
    $module_name = sfContext::getInstance()->getModuleName();
    $user_rel = '';
    switch ($module_name) {
      case 'prosecution':    
        $q->leftJoin($rootAlias.'.Group gr');
        $q->addWhere('gr.code=?', 'PRS'); 
        $user_rel = 'ProsecutionUserFiles';
        break;
      case 'agency': 
        $request = sfContext::getInstance()->getRequest();
        $code = $request->getParameter('code');
        
        // save code for redirections, only for this module where necessary to select by code
        if ($code) sfContext::getInstance()->getUser()->setAttribute('code', $code);
        else $code = sfContext::getInstance()->getUser()->getAttribute('code', 'CLD');

        if (!empty($code)) {
          $q->leftJoin($rootAlias.'.Group gr');
          $q->addWhere('gr.code=?', $code); 
          if ($code == 'PRI') $user_rel = 'PrisonUserFiles';
        }
        break;
    }
        
    return CommonTable::mainFilter($q, $this->getComponentName(), $user_rel);
  }
}