<?php

/**
 * AppealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Appeal');
    }
}