<?php

/**
 * BriefAdditionalMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BriefAdditionalMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BriefAdditionalMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BriefAdditionalMaterial');
    }
}