<?php

/**
 * BriefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BriefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BriefTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Brief');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    $q = CommonTable::mainFilter($q, $this->getComponentName());
    return $this->unreceived($q);
  }
  
  // display this list by default
  public function unreceived(Doctrine_Query $q)
  {
    //filter, complex filter conditions are only possible using tablemethod
    $request = sfContext::getInstance()->getRequest();
    if ($request->getParameter('rf')) {
      //$this->setFilters($this->configuration->getFilterDefaults());  // never used
      $filters_type = 'All';
      sfContext::getInstance()->getUser()->setAttribute('briefTableMethod', null);  // reset custom filter condition
    }
    else {      
      $filters_type = sfContext::getInstance()->getUser()->getAttribute('briefTableMethod', null);       
      if ($request->getParameter('filter')) {
        $filters_type = $request->getParameter('filter'); 
        sfContext::getInstance()->getUser()->setAttribute('briefTableMethod', $filters_type);
      }
      if ($filters_type) {
        $rootAlias = $q->getRootAlias();
        $q->andWhere('('.$rootAlias.'.status_id != 3 OR '.$rootAlias.'.status_id IS NULL)');
      }
    }
    
    return $q;
  }
  
}