<?php

/**
 * ChargeTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChargeTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChargeTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChargeType');
    }
}