<?php

/**
 * CommittalStreamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommittalStreamTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object CommittalStreamTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CommittalStream');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}