<?php

/**
 * CommittalStream
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CommittalStream extends BaseCommittalStream
{
  public function obtainClientId($module_name)
  {
    return $this->getUserFile()->getClientId();
  }
  
  public function obtainUserFileId($module_name)
  {
    return $this->getUserFileId();
  }
  
  public function getMentionDate()
  {
    return date('d F Y', strtotime($this->form_25_sent_date));
  }
}