<?php

/**
 * ComplianceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplianceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplianceTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Compliance');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    //return CommonTable::mainFilter($q, $this->getComponentName());
    return $q;
  }
}