<?php

/**
 * CorrespondenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorrespondenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorrespondenceTable
     */
  
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Correspondence');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}