<?php

/**
 * CourtDateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourtDateTable extends Doctrine_Table
{
  public $day = 86400;
  public $year = 31536000;
    /**
     * Returns an instance of this class.
     *
     * @return object CourtDateTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CourtDate');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
  
  
  public function getCurrentCourtDates(Doctrine_Query $q)
  {
    $years_ahead = date('Y-m-d', time() + 2*$this->year);
    $today = date('Y-m-d');
    
    $q = $this->mainFilter($q);
    $rootAlias = $q->getRootAlias();
    $q->andWhere($rootAlias.'.date >= ?', $today)
      ->andWhere($rootAlias.'.date <= ?', $years_ahead);

    return $q;
  }
   
  public function getPastCourtDates(Doctrine_Query $q)
  {
    $years_ago = date('Y-m-d', time() - 2*$this->year);
    $yesterday = date('Y-m-d', time() - $this->day);
    
    $q = $this->mainFilter($q);
    $rootAlias = $q->getRootAlias();
    
    if (strpos($q, 'uf') === false) {
      $q->leftJoin($rootAlias . '.UserFile uf');
    }
    $q->leftJoin('uf.Status st')
      ->andWhere('st.name <> ?', 'Closed')
      ->andWhere($rootAlias.'.date >= ?', $years_ago)
      ->andWhere($rootAlias.'.date <= ?', $yesterday);

    return $q;
  }
  
  public function getCourtDatesForUserFile()
  {
    $current_client = sfContext::getInstance()->getUser()->getAttribute('client', null);
    if ( ($current_client !== null) && ($current_client['last_file_id'] !== null) ) { 
      $file_id = $current_client['last_file_id']['id'];
      
      $q = $this->createQuery('cd');
      $q->leftJoin('cd.UserFile uf')
      ->andWhere('uf.id=?', $file_id);
      return $q;
    }
    
    return $this->createQuery('cd');

  }
  
}