<?php

/**
 * CourtNoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourtNoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourtNoteTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CourtNote');
  }
  
  public function mainFilter(Doctrine_Query $q)
  {
    //return CommonTable::mainFilter($q, $this->getComponentName());
    return $q;
  }
}