<?php

/**
 * CustodyVisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustodyVisitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustodyVisitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustodyVisit');
    }
}