<?php

/**
 * DisbursementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisbursementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisbursementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Disbursement');
    }
}