<?php

/**
 * DisbursementTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisbursementTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisbursementTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DisbursementType');
    }
}