<?php

/**
 * DocumentDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentDetail');
    }
}