<?php

/**
 * Document
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Document extends BaseDocument
{
  public function obtainClientId($module_name)
  {
    return $this->getUserFile()->getClientId();
  }
  
  public function obtainUserFileId($module_name)
  {
    return $this->getUserFileId();
  }
  
  public function getFileNumber()
  {
    return $this->getUserFile()->getNumber();
  }
  
  public function getCourtDateDate()
  {
    return ($this->getCourtDateId() !== null) ? $this->getCourtDate()->getDateFormatted('D, d M Y') : '';
  }
  
  static public function docExists($action_obj, $doc_obj0, $request, $which='arr')
  {
    //$info = CommonObject::getSessionUserFileData('all');
    $doc_obj = null;
    $doc_arr = array('txt' => '', 'id' => 0, 'buffer_id' => 0, 'load' => 'doc');
    $buffer_doc = self::getDocBuffer();

    $doc_id = ($doc_obj0) ? $doc_obj0->getId() : 0;                   // loaded document id.
    if ($buffer_doc) $doc_arr['buffer_id'] = $buffer_doc->getId();    // buffer document id.
    $buffer_doc_ref = ($buffer_doc) ? (int)$buffer_doc->getName() : 0;
    
    $checkbuffer0 = ($doc_id != $doc_arr['buffer_id']) && ($doc_arr['buffer_id'] > 0);
    $checkbuffer1 = !in_array(sfContext::getInstance()->getActionName(), array('update', 'create'));
    $checkbuffer2 = ( ($buffer_doc_ref == 0) || ( ($buffer_doc_ref > 0) && ($buffer_doc_ref != $doc_id) ) );
    
    // internal saved call NEVER check
    $checkbuffer3 = ($request->getParameter('_nrd')) ? false : true;  
    
    $checkbuffer = ($checkbuffer0 && $checkbuffer1 && $checkbuffer2 && $checkbuffer3);
    
    if ($checkbuffer) {
      $doc_type_id = ($buffer_doc) ? $buffer_doc->getDocumentTypeId() : 0;
//echo '=='.$doc_arr['buffer_id'].'==..'.$doc_type_id.'..';
      
      $check = empty($doc_type_id);   // do not check if valid buffer exists, must be saved first!
      if (!$check) {
        $doc_arr['load'] = 'buffer';
        $doc_arr['txt'] = "There is document data saved in your session buffer (".$buffer_doc->getDocumentType()->getName()."). ";
        $doc_arr['txt'].= " If it is not saved it will be lost! Do you want to load it?";
      }
    }
    
    $check = ($request->getParameter('id')) ? false : true;  // do not check if edition
    
    if ($action_obj->user_file && $action_obj->last_court_date && $check) {
      $doc_type = Doctrine::getTable('DocumentType')->findOneBy('short_name', $action_obj->helper->document_tpl_file);
      //$user = sfContext::getInstance()->getUser()->getGuardUser();
      
      $user_file_id = $action_obj->user_file->getId();
      $court_date_id = $action_obj->last_court_date->getId();
      $document_type_id = ($doc_type) ? $doc_type->getId() : 0;
      //$user_id = $user->getId();
      
      $sql_params = array($user_file_id, $court_date_id, $document_type_id/*, $user_id*/);
      $sql_str = 'user_file_id = ? AND court_date_id = ? AND document_type_id = ?'; //AND updated_by_id = ?';
      $docs = Doctrine::getTable('Document')->createQuery()
              ->where($sql_str, $sql_params)
              ->orderBy('updated_at DESC')
              ->execute();
      if ( $docs && (count($docs) > 0) ) {
        $doc_obj = $docs[count($docs)-1];   // more recent
        $user = Doctrine::getTable('SfGuardUser')->find($doc_obj->getUpdatedById());
        $user_name = ($user) ? $user->obtainFullName() : '';
        
        $doc_arr['txt'] = "The most recent '".$doc_type->getName()."' document for the current user file and court date ";
        $doc_arr['txt'].= "was updated by ".$user_name.". Do you want to load it?";
        $doc_arr['id'] = $doc_obj->getId();
      }
    }
    
    return ($which == 'obj') ? $doc_obj : $doc_arr;
  }
  
  
  // get the document id for the session buffer for the current user
  static public function getDocBuffer()
  {
    $user = sfContext::getInstance()->getUser()->getGuardUser();
    $docs = Doctrine::getTable('Document')->findBySql('description = ? AND updated_by_id =?', array("buffer", $user->getId()));
    return ( $docs && (count($docs) > 0) ) ? $docs[count($docs)-1] : null;
  }
  
  
  static public function clearDocBuffer()
  {
    $user = sfContext::getInstance()->getUser()->getGuardUser();
    $docs = Doctrine::getTable('Document')->findBySql('description = ? AND updated_by_id =?', array("buffer", $user->getId()));
    if ( $docs && (count($docs) > 0) ) {
      $docs[count($docs)-1]->setDocumentTypeId(0);
      $docs[count($docs)-1]->setName("");
      $docs[count($docs)-1]->save();
    }
  }
  
  static public function setDocBuffer($docid)
  {
    if (sfContext::getInstance()->getModuleName() == 'document') {
      $user = sfContext::getInstance()->getUser()->getGuardUser();
      $docs = Doctrine::getTable('Document')->findBySql('description = ? AND updated_by_id =?', array("buffer", $user->getId()));
      if ( $docs && (count($docs) > 0) && ($docs[count($docs)-1]->getId() != $docid) ) {
        $docs[count($docs)-1]->setName($docid);   // save the id of the document whose data is saving
        $docs[count($docs)-1]->save();
      }
    }
  }
  
  public function getCommittalMentionDate($user_file)
  {
    $cmd = '';
    if ($user_file) {
      $court_dates = $user_file->getFileCourtDates();
      foreach ($court_dates as $cd) {
        if (strtolower($cd->getListing()->getName()) == 'committal mention') {
          $cmd = $cd->getDate();
          if ($cmd != '') $cmd = date('j F Y', strtotime($cmd));
          break;
        }
      }
    }
      
    return $cmd;
  }
  
}