<?php

/**
 * DocumentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DocumentType extends BaseDocumentType
{
  // added by William, 02/06/2013: buffer document saves extra record for this object, to avoid it request name
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setName(trim($this->getName()));
    if ($this->getName()) {
      return parent::save();
    }
    else {
      return null;
    }
  }
}