<?php

/**
 * DocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Document');
  }

  public function retrieveValidDocumentList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    //$q->addWhere($rootAlias . '.document_type_id != ?', 0);
    $q->addWhere("(".$rootAlias.".description IS NULL OR ".$rootAlias.".description != 'buffer')");
    return $q;
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    $q = $this->retrieveValidDocumentList($q);
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}