<?php

/**
 * FeeAgreement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FeeAgreement extends BaseFeeAgreement
{
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setLumpSum(trim($this->getLumpSum()));
    $this->setHourlyFee(trim($this->getHourlyFee()));
    
    // only save if there is an amount to save.
    if ( $this->getLumpSum() || $this->getHourlyFee() ) {
      return parent::save();
    }
    else {
      return null;
    }
  }
  
  public function calculateAmountGst($amount=0, $direction='direct')
  {
    //if ($this->getGst() != '') return $this->getGst();
    
    if ($amount == 0) $amount = $this->getLumpSum();
    $gst = sfConfig::get("app_gst");
    
    if ($direction == 'direct') {
      $gst_amount = ($amount/100)*$gst;
    }
    else {
      $gst_amount = ($amount)*($gst/(100+$gst));
    }
    return number_format($gst_amount, sfConfig::get("app_precision"));
  }
}