<?php

/**
 * FeeDetailTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeDetailTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeeDetailTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeeDetailType');
    }
}