<?php

/**
 * FeeDetailType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FeeDetailType extends BaseFeeDetailType
{
  public function getValueForId()
  {
    return strtolower(str_replace(' ', '_', $this->getValue()));
  }
}