<?php

/**
 * FeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeeTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Fee');
  }
    
  public function mainFilter(Doctrine_Query $q)
  {
    //return CommonTable::mainFilter($q, $this->getComponentName());
    return $q;
  }
}