<?php

/**
 * FileNoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileNoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileNoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileNote');
    }
    
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}