<?php

/**
 * FileAttachement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FileAttachement extends BaseFileAttachement
{
  public function generateDocumentFileFilename(sfValidatedFile $validator)
  {
    $arr = explode('.', $validator->getOriginalName());
    $filenameBase = implode('.', array_slice($arr, 0, sizeof($arr)-1));
    if (!file_exists($validator->getPath().'/'.$validator->getOriginalName())) {
      return $validator->getOriginalName();
    }

    $i = 1;
    while (1) {
      $newFilename = sprintf('%s-%s%s', basename($filenameBase), $i, $validator->getOriginalExtension());
      if (!file_exists($validator->getPath().'/'.$newFilename)) {
        return $newFilename;
      }
      $i++;
    }
    
  }
  
  public function getUpdatedBy()
  {
    return $this->getUser()->obtainFullName();
  }
  
  
  /*public function postDelete($values)
  {
    $filename = $this->getAttachment();
    $entry_number = $this->getShipment()->getEntryNumber();
    
    $filepath = sfConfig::get('sf_upload_dir').DIRECTORY_SEPARATOR.$entry_number.DIRECTORY_SEPARATOR.$filename;
    @unlink($filepath);
  }*/

}