<?php

/**
 * FileAttachementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileAttachementTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object FileAttachementTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('FileAttachement');
  }
  
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}