<?php

/**
 * InvoiceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvoiceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceType');
    }
}