<?php

/**
 * PreferredContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreferredContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreferredContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreferredContact');
    }
}