<?php

/**
 * ReceiptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Receipt');
  }
  
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}