<?php

/**
 * ReferralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Referral');
    }
}