<?php

/**
 * SentByTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SentByTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SentByTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SentBy');
    }
}