<?php

/**
 * SettingParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SettingParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SettingParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SettingParam');
    }
}