<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
  public function getDobDetail()
  {
    $date = new DateTime($this->getDob());
    $diff = $date->diff(new DateTime());
    return 'Age:  '.$diff->y.' years and '.$diff->m.' months';
    //printf("%d months and %d days old", $diff->y*12 + $diff->m, $diff->d);
  }
  
  public function getFullAddress()
  {
    return $this->getStreet()."\n".$this->getSuburb()."\n".$this->getState()." ".$this->getPostcode();
  }
  
  public function getDobFormatted($format='')
  {
    return ($format != '') ? date($format, strtotime($this->getDob())) : $this->getDob();
  }
  
  public function getContactData($option='p&f')
  {
    $phones_arr = array(
        'home' => trim($this->getHomePhone()),  'work' => trim($this->getWorkPhone()), 
        'mobile' => trim($this->getMobile()),   'other' => trim($this->getOtherPhone())
        );
    
    $phones = implode("/", array_filter($phones_arr));
    if ($option == 'ical') {  // for court date iCal only
      $contact_info = $phones;
    }
    else {
      $contact_info_arr[] = ($phones != "") ? "Phones: ".$phones : "";
      $contact_info_arr[] = (trim($up->getFax()) != '') ? "Fax: ".trim($up->getFax()) : "";
        
      $contact_info = implode("\n", array_filter($contact_info_arr));
    }
    
    return $contact_info;
  }
}