<?php

/**
 * sfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends Doctrine_Table
{
  static public $states = array(
    'VIC' => 'Victoria',
    'ACT' => 'Australian Capital Territory',
    'NSW' => 'New South Wales',
    'NT' => 'Northern Territory',
    'QLD' => 'Queensland ',
    'SA' => 'South Australia',
    'TAS' => 'Tasmania',
    'WA' => 'Western Australia'
  );
  
  /**
    * Returns an instance of this class.
    *
    * @return object sfGuardUserProfileTable
    */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('sfGuardUserProfile');
  }
    
  public function getStates()
  {
    return self::$states;
  }
  
  public function getFilterStates()
  {
    return array_merge(array('' => ''), self::$states);
  }
}