<?php

/**
 * sfGuardUserAgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserAgencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserAgencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserAgency');
    }
}