<?php

/**
 * ShortMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShortMessageTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object ShortMessageTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ShortMessage');
  }
  
  public function mainFilter(Doctrine_Query $q)
  {
    return CommonTable::mainFilter($q, $this->getComponentName());
  }
}