<?php

/**
 * ShortMessageTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShortMessageTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShortMessageTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShortMessageTemplate');
    }
}