<?php

/**
 * StatusTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusType');
    }
}