<?php

/**
 * StatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object StatusTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Status');
  }
  
  public function getStatusByType($short_name)
  {
    $q = $this->createQuery('ss');
    $q->leftJoin('ss.StatusType st')
    ->andWhere('st.short_name=?', $short_name);
    return $q;
  }
    
  public function getBriefStatus()            { return $this->getStatusByType('BRI'); }
  
  public function getUserFileStatus()         { return $this->getStatusByType('UFS'); }
  
  public function getVLAApplicationStatus()   { return $this->getStatusByType('VLA'); }
  
  public function getACBCertificateStatus()   { return $this->getStatusByType('ACB'); }
  
  public function getCurrentAidStatus()       { return $this->getStatusByType('LCA'); }
  
  public function getPaymentDocumentsStatus() { return $this->getStatusByType('PDS'); }
  
  public function getActiveInactiveStatus()   { return $this->getStatusByType('ACI'); }
  
}