<?php

/**
 * SubgroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubgroupTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object SubgroupTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Subgroup');
  }
    
  // to load agency combo boxes values by group
  public function getSubGroupsByGroupCB($code)
  {
    $q = $this->createQuery('sg');
    $q->leftJoin('sg.Group gg')
    ->andWhere('gg.code=?', $code);
    return $q;
  }
  
  public function getProsecutionSubGroupsCB()
  {
    return $this->getSubGroupsByGroupCB('PRS');
  }
  
  public function getCourtSubGroupsCB()
  {
    return $this->getSubGroupsByGroupCB('COU');
  }
}