<?php

/**
 * WhoLiveWithTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WhoLiveWithTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WhoLiveWithTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WhoLiveWith');
    }
}