generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FileNote
    theme:                 zafire
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          file_note
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        batch_actions: {}
      filter:  ~
      form:    
        actions: {}
      edit:    
        actions: 
          _save:
          _list:
        #return_to: edit
      ajaxedit: ~
      new:     
        actions: 
          _save:
          _list:
        #return_to: edit
      show:    ~
      
