<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
  /**
    * Returns an instance of this class.
    *
    * @return object sfGuardGroupTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('sfGuardGroup');
  }
  
  static function getIdByCode($code)
  {
    $q = Doctrine_Query::create();
    $object = $q->select('id')
      ->from('SfGuardGroup g')
      ->where('g.code=?', $code)
      ->fetchOne();
    return ($object) ? $object['id'] : null;
  }
    
  public function getClientGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'CLI');
    return $q;
  }
  
  public function getInformantGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'INF');
    return $q;
  }
  
  public function getBarristerGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'BAR');
    return $q;
  }
  
  public function getClerkGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'CLE');
    return $q;
  }
  
  public function getProsecutorGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'PRO');
    return $q;
  }
  
  public function getJudgeGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'JUD');
    return $q;
  }
  
  public function getMagistrateGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'MAG');
    return $q;
  }
  
  public function getJudgeMagistrateGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'JUD');
    $q->orWhere('g.code=?', 'MAG');
    return $q;
  }
  
  public function getCoordinatorGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'COO');
    return $q;
  }
  
  public function getAssociateGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'ASS');
    return $q;
  }
  
  
  // for agencies
  public function getPRIGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'PRI');
    return $q;
  }
  
  public function getCLDGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'CLD');
    return $q;
  }
  
  public function getOOCGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'OOC');
    return $q;
  }
  
  public function getJJSGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'JJS');
    return $q;
  }
  
  public function getALSGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'ALS');
    return $q;
  }
  
  public function getCLSGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'CLS');
    return $q;
  }
  
  public function getACBGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'ACB');
    return $q;
  }
  
  public function getPRSGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'PRS');
    return $q;
  }
  
  public function getPOLGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'POL');
    return $q;
  }
  
  public function getCOUGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'COU');
    return $q;
  }
  
  public function getVLAGroupId()
  {
    $q = $this->createQuery('g');
    $q->where('g.code=?', 'VLA');
    return $q;
  }
  
  
  // to load groups combo boxes values by category (description)
  public function getGroupsByCategoryCB($category)
  {
    $q = $this->createQuery('gr')
    ->where('gr.description=?', $category)
    ->orderBy('gr.name ASC');
    return $q;
  }
    
  public function getUsersCB()      { return $this->getGroupsByCategoryCB('USER'); }
    
  public function getAgenciesCB()      { return $this->getGroupsByCategoryCB('AGENCY'); }
}