generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 zafire
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [first_name, last_name, email_address, username, group, updated_at]
        max_per_page: 20
        batch_actions: {}
      filter:
        class: UserFormFilter
      form:
      edit:
        actions:
          _delete:
          _list:
          _save:
        #return_to: edit
      ajaxedit: ~
      new:  
        actions:
          _list:
          _save:
        #return_to: edit
      show:    ~
      
