generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ShortMessage
    theme:                 zafire
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          short_message
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: SMS List
        display: [sms_from, sms_to, user, user_file, message, updated_at]
        max_per_page: 10
        batch_actions: {}
        object_actions: 
          _show:     ~
          _delete:  ~
      filter:  
        display: [sms_from, sms_to, user_id, user_file_id, updated_at]
      form:    ~
      edit:    
        title: Edit SMS
        actions: 
          _list:
        #return_to: edit
      ajaxedit: ~
      new:     
        title: New SMS
        actions: 
          _save:
            label: Send
          _list:
        #return_to: edit
      show:    ~
      
