# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:  
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, shadowbox.css, /js/printPreview/css/print-preview.css, /css/document/screen.css, /js/chosen/chosen.css, /css/document/print.css { media: print }]
  #stylesheets:    [/sfDoctrinePlugin/css/default.css, /sfDoctrinePlugin/css/global.css, main.css]

  javascripts:    
    - jquery-1.5.1.min.js
    - appowner.js
    - shadowbox.js
    - /js/printPreview/jquery.print-preview.js
    - /js/chosen/chosen.jquery.js
    - jquery.maskedinput-1.2.2.js
    - jquery-ui-1.8.16.custom.min.js
    - jquery.json-2.3.js
    - jquery.jeditable.js

  has_layout:     true
  layout:         form_layout
  
  printPreviewSuccess:
    layout: print_layout